export const TRANSCRIPTION_TEXT = `# Phaistos Disc transcription (Evans sign numbers)
# Side A:
¦02 12 13 01 18/
| 24 40 12 | 29 45 07/
| 29 29 34 | 02 12 04 40 33 | 27 45 07 12 | 27 44 08 | 02 12 06 18 ?? | 31 26 35 | 02 12 41 19 35 | 01 41 40 07 | 02 12 32 23 38/
| 39 11 | ^ 02 27 25 10 23 18 | 28 01/
| 02 12 31 26/
| 02 12 27 27 35 37 21 | 33 23 | 02 12 31 26/
| 02 27 25 10 23 18 | 28 01/
| 02 12 31 26/
| 02 12 27 14 32 18 27 | 06 18 17 19/
| 31 26 12 | 02 12 13 01 | 23 19 35/
| 10 03 38 | 02 12 27 27 35 37 21 | 13 01 | 10 03 38
# Side B:
¦02 12 22 40 07 | 27 45 07 35 | 02 37 23 05/
| 22 25 27 | 33 24 20 12 | 16 23 18 43/
| 13 01 39 33 | 15 07 13 01 18 | 22 37 42 25 | 07 24 40 35 | 02 26 36 40 | 27 25 38 01 | 29 ^ 24 24 20 35 | 16 14 18 | 29 33 01 | 06 35 32 39 33 | 02 09 27 01 | 29 36 07 08/
| 29 08 13 | 29 45 07/
| 22 29 36 07 08/
| 27 34 23 25 | 07 18 35 | 07 45 07/
| 07 23 18 24 | 22 29 36 07 08/
| 09 30 39 18 07 | 02 06 35 23 07 | 29 34 23 25 | 45 07/
`;

export const PHONETIC = new Map([
  [1,  { v: "je",  c: "low-med" }],
  [2,  { v: "°",   c: "det" }],
  [3,  { v: "u",   c: "low-med" }],
  [4,  { v: "nwa", c: "low" }],
  [5,  { v: "pu",  c: "low" }],
  [6,  { v: "de",  c: "low" }],
  [7,  { v: "ti",  c: "med" }],
  [8,  { v: "no",  c: "low-med" }],
  [9,  { v: "pe",  c: "med" }],
  [10, { v: "zu",  c: "med" }],
  [11, { v: "twe", c: "low" }],
  [12, { v: "qe",  c: "HIGH" }],
  [13, { v: "pa",  c: "low" }],
  [14, { v: "ta",  c: "low" }],
  [15, { v: "so",  c: "low-med" }],
  [16, { v: "ze",  c: "low-med" }],
  [17, { v: "?17", c: "none" }],
  [18, { v: "ti",  c: "med", note: "allograph of 07" }],
  [19, { v: "sa",  c: "HIGH" }],
  [20, { v: "ra",  c: "low-med" }],
  [21, { v: "swi", c: "med-hi" }],
  [22, { v: "zo",  c: "low" }],
  [23, { v: "na",  c: "low-med" }],
  [24, { v: "e",   c: "low-med" }],
  [25, { v: "dwa", c: "low" }],
  [26, { v: "rja", c: "med", note: "CORRECTED: AB76 RA2, not AB77 KA" }],
  [27, { v: "wi",  c: "low" }],
  [28, { v: "re",  c: "low-med" }],
  [29, { v: "ma",  c: "HIGH" }],
  [30, { v: "me",  c: "low" }],
  [31, { v: "ku",  c: "HIGH" }],
  [32, { v: "ra2", c: "low", note: "tentative; distinct from PD20 ra (AB60)" }],
  [33, { v: "sa",  c: "med", note: "allograph of 19" }],
  [34, { v: "pi",  c: "low-med" }],
  [35, { v: "te",  c: "med" }],
  [36, { v: "ni",  c: "low-med" }],
  [37, { v: "tu",  c: "low-med" }],
  [38, { v: "ka",  c: "low-med", note: "CORRECTED: AB77 KA, not AB38 E" }],
  [39, { v: "i",   c: "med" }],
  [40, { v: "ru",  c: "low-med" }],
  [41, { v: "si",  c: "low" }],
  [42, { v: "mi",  c: "low" }],
  [43, { v: "tja", c: "low-med" }],
  [44, { v: "di",  c: "med" }],
  [45, { v: "rja", c: "med" }],
]);

export const RASMUSSEN_PHONETIC = new Map([
  [1, "pa"], [2, "is"], [3, "si"], [4, "ap"], [5, "pu"], [6, "wa"],
  [7, "ti"], [8, "ki"], [9, "hut"], [10, "u"], [11, "ar"], [12, "ku"],
  [13, "kwe"], [14, "tu"], [15, "at"], [16, "a"], [17, "ke"], [18, "ra"],
  [19, "lu"], [20, "li"], [21, "we"], [22, "isk"], [23, "sa"], [24, "ma"],
  [25, "ha"], [26, "wi"], [27, "la"], [28, "za"], [29, "mi"], [30, "ija"],
  [31, "ka"], [32, "i"], [33, "pi"], [34, "zi"], [35, "ta"], [36, "vi"],
  [37, "se"], [38, "hi"], [39, "na"], [40, "it"], [41, "va"], [42, "ru"],
  [43, "su"], [44, "he"], [45, "ja"],
]);

export const LINEAR_A_WORDS = [
  { w: "a-ta-i-*301-wa-ja", src: "IO Za 2, PK Za 11", note: "libation formula opening" },
  { w: "ja-di-ki-tu", src: "IO Za 2", note: "libation formula — vessel term" },
  { w: "ja-sa-sa-ra-me", src: "IO Za 2, PK Za 11+", note: "divine epithet 'lady'?" },
  { w: "u-na-ka-na-si", src: "IO Za 2", note: "libation formula" },
  { w: "i-pi-na-ma", src: "IO Za 2, PK Za 11", note: "'I distribute'?" },
  { w: "si-ru-te", src: "IO Za 2", note: "cf. PD B23 (Owens)", pdInspired: true },
  { w: "ta-na-ra-te", src: "IO Za 2", note: "cf. PD B25 (Owens)", pdInspired: true },
  { w: "u-ti-nu", src: "IO Za 2", note: "libation formula" },
  { w: "i-*301-wa-ja", src: "IO Za 2, PK Za 11", note: "'olive oil'" },
  { w: "i-*301-wa-e", src: "PK Za 11", note: "variant of above" },
  { w: "da-pi-te-ri", src: "PK Za 11", note: "'stone (material)'" },
  { w: "a-di-ki-te-te", src: "PK Za 11", note: "vessel designation" },
  { w: "tu-me-i", src: "PK Za 11, PK Za 8", note: "libation formula" },
  { w: "u-na-ru-ka-na-ti", src: "PK Za 11", note: "cf. PD B28-29 (Owens)", pdInspired: true },
  { w: "ma-te-re-sa", src: "PH 15a", note: "cf. PD B16 -re-sa", pdInspired: true },
  { w: "ti-di-te", src: "KN Zf 31", note: "cf. PD B24", pdInspired: true },
  { w: "ti-di-te-qa-ti", src: "KN Zf 31", note: "extended form" },
  { w: "ma-ka-ri-te", src: "HT 117a", note: "compound phrase" },
  { w: "na-da-re", src: "HT 117a", note: "cf. PD A27 na-da-te?", pdInspired: true },
  { w: "da-ru-ne-te", src: "HT 98 b.2", note: "cf. -ne-te suffix" },
  { w: "ka-ku-ne-te", src: "ZA 10 b.6", note: "cf. -ne-te suffix" },
  { w: "ku-ro", src: "multiple", note: "'total'" },
  { w: "ki-ro", src: "multiple", note: "'crossroads'?" },
  { w: "qe-ku-re", src: "multiple", note: "'underground'?" },
  { w: "ti-ti-ku", src: "HT 86a", note: "reduplicated TI" },
  { w: "pi-rju-te", src: "HT 116a.4", note: "cf. PD -rju-te", pdInspired: true },
  { w: "ja-sa-ja", src: "KN Zg 55", note: "cf. PD B15 (Owens)", pdInspired: true },
  { w: "ja-si-e", src: "KE Zb 4", note: "variant" },
  { w: "i-da-ma-na", src: "AR Zf 1, AR Zf 2", note: "Arkalochori Axe" },
  { w: "si-da-te", src: "ARKH 2.1", note: "cf. PD A10 (Owens)", pdInspired: true },
  { w: "ku-ra", src: "ZA 20.4", note: "cf. PD A9 (Owens)", pdInspired: true },
  { w: "sa-sa-ma", src: "multiple", note: "'sesame'" },
  { w: "ku-mi-no", src: "HT 97", note: "'cumin'" },
  { w: "a-sa-sa-ra-ma-na", src: "PK Za 11", note: "extended epithet" },
];

// Linear A entries whose `note` cites a Phaistos Disc parallel (`cf. PD …`). These 10 of 34
// entries (~29%) were curated against PD parallels; the leave-PD-out test re-runs the Minoan
// comparison with only the 24 PD-uncited entries to quantify how much of the Minoan signal
// depends on this curation overlap. See paper §2.3 / §2.6.
export const LINEAR_A_WORDS_NO_PD_INSPIRED = LINEAR_A_WORDS.filter(w => !w.pdInspired);

export const GREEK_WORDS = [
  { w: "wa-na-ka",        src: "PY Er 312+", note: "king (ϝάναξ)" },
  { w: "po-ti-ni-ja",     src: "PY Tn 316+", note: "mistress/lady (πότνια)" },
  { w: "ti-ri-po",        src: "PY Ta 641",  note: "tripod (τρίπους)" },
  { w: "ti-ri-po-de",     src: "PY Ta 641",  note: "tripods (τρίποδες)" },
  { w: "ko-wa",           src: "PY Aa+",     note: "girl (κόρϝα)" },
  { w: "ko-wo",           src: "PY Aa+",     note: "boy (κόρϝος)" },
  { w: "e-ra-wo",         src: "KN Fh+",     note: "olive oil (ἔλαιϝον)" },
  { w: "ku-mi-no",        src: "HT 97",      note: "cumin (κύμινον) — also LA" },
  { w: "to-so",           src: "KN+PY",      note: "so much (τόσσος)" },
  { w: "do-e-ro",         src: "PY+KN",      note: "slave (δοῦλος)" },
  { w: "do-e-ra",         src: "PY+KN",      note: "slave girl (δούλη)" },
  { w: "ka-ko",           src: "PY Jn+",     note: "bronze (χαλκός)" },
  { w: "ku-ru-so",        src: "PY+KN",      note: "gold (χρυσός)" },
  { w: "ri-no",           src: "KN L+",      note: "flax (λίνον)" },
  { w: "si-to",           src: "KN+PY",      note: "wheat (σῖτον)" },
  { w: "wo-no",           src: "KN+PY",      note: "wine (ϝοῖνος)" },
  { w: "me-ri",           src: "KN Gg+",     note: "honey (μέλι)" },
  { w: "i-qo",            src: "KN Ca+",     note: "horse (ἵππος)" },
  { w: "te-me-no",        src: "PY Er+",     note: "shrine (τέμενος)" },
  { w: "te-o",            src: "KN+PY",      note: "god (θεός)" },
  { w: "te-o-jo",         src: "PY Un+",     note: "of the god (θεοῖο)" },
  { w: "da-mo",           src: "PY Ep+",     note: "municipality (δᾶμος)" },
  { w: "pa-te",           src: "PY Fn+",     note: "father (πατήρ)" },
  { w: "ma-te",           src: "PY Fr+",     note: "mother (μάτηρ)" },
  { w: "tu-ka-te",        src: "PY+MY",      note: "daughter (θυγάτηρ)" },
  { w: "pe-ma",           src: "PY Un+",     note: "grain (σπέρμα)" },
  { w: "ra-wo",           src: "KN+PY",      note: "people (λαϝός)" },
  { w: "ne-wo",           src: "KN+PY",      note: "new (νέϝος)" },
  { w: "to-ra-ka",        src: "KN Sk+",     note: "armor (θώρακα)" },
  { w: "ki-to",           src: "KN+PY",      note: "tunic (χιτών)" },
  { w: "qa-si-re-u",      src: "KN+PY",      note: "leader (κϝασιλεύς)" },
  { w: "i-je-re-u",       src: "PY+KN",      note: "priest (ἱερεύς)" },
  { w: "i-je-re-ja",      src: "PY+KN",      note: "priestess (ἱέρεια)" },
  { w: "ka-ke-u",         src: "PY Jn+",     note: "coppersmith (χαλκεύς)" },
  { w: "na-u-do-mo",      src: "PY An+",     note: "shipwright (ναυδόμος)" },
  { w: "te-ko-to-ne",     src: "PY An+",     note: "carpenters (τέκτονες)" },
  { w: "e-re-ta",         src: "PY An+",     note: "rowers (ἐρέται)" },
  { w: "po-me",           src: "KN Da+",     note: "shepherd (ποιμήν)" },
  { w: "po-me-no",        src: "KN Da+",     note: "shepherd gen. (ποιμένος)" },
  { w: "e-ke",            src: "PY+KN",      note: "has (ἔχει)" },
  { w: "do-se",           src: "PY+KN",      note: "he gives (δώσει)" },
  { w: "pe-re",           src: "PY+KN",      note: "to bring (φέρειν)" },
  { w: "de-do-me-na",     src: "PY+KN",      note: "things offered (δεδομένα)" },
  { w: "e-e-si",          src: "PY+KN",      note: "they are (ἔενσι)" },
  { w: "ko-no-so",        src: "KN",         note: "Knossos" },
  { w: "pa-i-to",         src: "KN",         note: "Phaistos" },
  { w: "a-mi-ni-so",      src: "KN Fp+",     note: "Amnisos" },
  { w: "tu-ri-so",        src: "KN+PY",      note: "Tylissos" },
  { w: "di-ka-ta",        src: "KN Fp+",     note: "Dikte (sanctuary)" },
  { w: "a-to-ro-po",      src: "PY+KN",      note: "man (ἄνθρωπος)" },
  { w: "me-ta",           src: "PY+KN",      note: "after/with (μετά)" },
  { w: "a-pu",            src: "PY+KN",      note: "from (ἀπύ)" },
  { w: "e-pi",            src: "PY+KN",      note: "on (ἐπί)" },
  { w: "u-po",            src: "PY+KN",      note: "under (ὑπό)" },
  { w: "pa-sa",           src: "PY+KN",      note: "all fem. (πᾶσα)" },
  { w: "ke-ra",           src: "KN+PY",      note: "horn (κέρας)" },
  { w: "to-pe-za",        src: "PY+KN",      note: "table (τράπεζα)" },
  { w: "e-re-pu",         src: "PY+KN",      note: "ivory (ἐλέφας)" },
  { w: "a-ko-ra",         src: "PY+KN",      note: "assembly (ἀγορά)" },
  { w: "ku-na-ja",        src: "PY+KN",      note: "woman (γυναία)" },
  { w: "ko-pi-na",        src: "PY+KN",      note: "basket (κόφινας)" },
  { w: "ka-po",           src: "PY+KN",      note: "fruit (καρπός)" },
  { w: "e-re-u-te-ro",    src: "PY+KN",      note: "free (ἐλεύθερος)" },
  { w: "a-pi-po-re-we",   src: "PY+KN",      note: "amphora (ἀμφιφορεύς)" },
  { w: "po-pu-re-ja",     src: "PY+KN",      note: "purple (πορφύρεια)" },
  { w: "ke-ro-si-ja",     src: "PY+KN",      note: "council of elders (γερουσία)" },
  { w: "i-je-ro-jo",      src: "PY+KN",      note: "holy gen. (ἱεροῖο)" },
];

export const LUWIAN_WORDS = [
  { w: "ta-ti",          src: "CLuw corpus",    note: "father (tati-)" },
  { w: "na-ni",          src: "CLuw corpus",    note: "brother (nani-)" },
  { w: "a-ni",           src: "CLuw corpus",    note: "mother (anni-)" },
  { w: "wa-na-ti",       src: "CLuw corpus",    note: "woman (wanatti-)" },
  { w: "zi-ti",          src: "HLuw corpus",    note: "man/person (ziti-)" },
  { w: "ha-sa-mi",       src: "CLuw corpus",    note: "clan/people (hasami-)" },
  { w: "na-na-sa-ri",    src: "CLuw corpus",    note: "sister (nanašri-)" },
  { w: "ha-sa",          src: "CLuw corpus",    note: "grandson (hamša-)" },
  { w: "ti-de-mi",       src: "CLuw corpus",    note: "son (tideimi-)" },
  { w: "hu-ta-ri",       src: "CLuw corpus",    note: "servant (hutarli-)" },
  { w: "ha-su",          src: "CLuw/HLuw",      note: "king (hassuw-)" },
  { w: "ma-sa-na",       src: "HLuw corpus",    note: "god/deity (maššana-)" },
  { w: "ta-ru-ti",       src: "HLuw corpus",    note: "storm god (Tarhunt-), CV approx" },
  { w: "ti-wa-ti",       src: "HLuw corpus",    note: "sun god (Tiwat-)" },
  { w: "a-ri-ma",        src: "HLuw corpus",    note: "moon/moon god (arma-)" },
  { w: "ha-ta-wa-ti",    src: "HLuw corpus",    note: "great king (hantawati-)" },
  { w: "pa-ri-na",       src: "CLuw corpus",    note: "house (parna-)" },
  { w: "ha-pi",          src: "CLuw corpus",    note: "river (hapi-)" },
  { w: "ha-wi",          src: "CLuw corpus",    note: "sheep (hawi-)" },
  { w: "da-ka-mi",       src: "CLuw corpus",    note: "ground/earth (dakam-)" },
  { w: "ma-du",          src: "CLuw corpus",    note: "honey (maddu-)" },
  { w: "wa-ri-wa",       src: "CLuw corpus",    note: "lion (walwa-)" },
  { w: "pa-ti",          src: "CLuw corpus",    note: "foot (pati-)" },
  { w: "ka-ru-ti",       src: "CLuw corpus",    note: "turn/circle (kaluti-)" },
  { w: "ti-ya-mi",       src: "CLuw corpus",    note: "ground (tijammi-)" },
  { w: "ta-wi",          src: "CLuw corpus",    note: "eye (tawi-)" },
  { w: "i-sa-ri",        src: "CLuw corpus",    note: "hand (iššari-)" },
  { w: "ta-pa-sa",       src: "CLuw corpus",    note: "sky (tappaš-)" },
  { w: "ra-ri",          src: "CLuw corpus",    note: "language (lali-)" },
  { w: "ma-mi-ya-na",    src: "CLuw corpus",    note: "word (mammijan-)" },
  { w: "ta-si",          src: "HLuw corpus",    note: "stone stele (tasi-)" },
  { w: "u-sa",           src: "CLuw corpus",    note: "year (ušša-)" },
  { w: "wi-ni-ya-ti",    src: "CLuw corpus",    note: "wine (winijant-)" },
  { w: "tu-ri-pi",       src: "HLuw corpus",    note: "bread (TURPI logogram)" },
  { w: "ku-wa-za",       src: "CLuw corpus",    note: "copper (kuwanza)" },
  { w: "ta-ru-pi",       src: "CLuw corpus",    note: "clay (taluppi-)" },
  { w: "wa-si-na",       src: "CLuw corpus",    note: "body (wassina-)" },
  { w: "a-ri-ka-ma-na",  src: "CLuw corpus",    note: "tribute (arkammana-)" },
  { w: "pa-ri-ha-sa",    src: "CLuw corpus",    note: "shield (palahša-)" },
  { w: "i-ya",           src: "CLuw corpus",    note: "to make/do (iya-)" },
  { w: "pi-ya",          src: "CLuw corpus",    note: "to give (piya-)" },
  { w: "da",             src: "CLuw corpus",    note: "to take/give (da-)" },
  { w: "ti-ya",          src: "CLuw corpus",    note: "to step/set (tiya-)" },
  { w: "tu-wa",          src: "CLuw corpus",    note: "to put (tuwa-)" },
  { w: "a-ku",           src: "CLuw corpus",    note: "to drink (aku-)" },
  { w: "wa-ri",          src: "CLuw corpus",    note: "to help (war-)" },
  { w: "ma-na",          src: "CLuw corpus",    note: "to pronounce (mana-)" },
  { w: "ha-ri-ta",       src: "CLuw corpus",    note: "to call (halta-)" },
  { w: "ta-ri-ku-mi-ya", src: "CLuw corpus",    note: "to announce (tarkummija-)" },
  { w: "a-pa",           src: "CLuw corpus",    note: "that/this (apa-, demonstrative)" },
  { w: "a-da",           src: "CLuw corpus",    note: "in/inside (anda)" },
  { w: "a-ri-ha",        src: "CLuw corpus",    note: "away (arha)" },
  { w: "pa-ra",          src: "CLuw corpus",    note: "forward/across (para)" },
  { w: "pa-ri",          src: "CLuw corpus",    note: "forward (pari)" },
  { w: "na-wa",          src: "CLuw corpus",    note: "not (nawa)" },
  { w: "na-nu",          src: "CLuw corpus",    note: "now (nanun)" },
  { w: "sa-ri",          src: "CLuw corpus",    note: "above/up (šarri)" },
  { w: "ku-wi",          src: "CLuw corpus",    note: "which/that (kui-, relative)" },
  { w: "pa-ya-tu",       src: "Achterberg 2004", note: "Phaistos (proposed)" },
  { w: "ku-na-sa",       src: "Achterberg 2004", note: "Knossos (proposed)" },
  { w: "ra-su-ta",       src: "Achterberg 2004", note: "Lasithi (proposed)" },
  { w: "hi-ya-wa",       src: "Achterberg 2004", note: "Ahhiyawa (proposed)" },
  { w: "ri-ti-na",       src: "Achterberg 2004", note: "Rhytion (proposed)" },
  { w: "na-sa-tu",       src: "Achterberg 2004", note: "Nestor (proposed)" },
  { w: "na-sa-ti",       src: "Achterberg 2004", note: "Nestor dative (proposed)" },
  { w: "wi-ru-si-ya",    src: "HLuw corpus",    note: "Wilusa/Troy" },
  { w: "a-ri-za-wa",     src: "HLuw corpus",    note: "Arzawa" },
  { w: "ka-ri-ka-mi-sa", src: "HLuw corpus",    note: "Karkamis/Carchemish" },
  { w: "u-ra",           src: "CLuw corpus",    note: "big/great (ura-)" },
  { w: "wa-su",          src: "CLuw corpus",    note: "good (wašu-)" },
  { w: "pa-ri-ha",       src: "CLuw corpus",    note: "wide (palha-)" },
  { w: "ha-ra-ri",       src: "CLuw corpus",    note: "pure/clean (halali-)" },
];

export const SEMITIC_WORDS = [
  { w: "i-ru",           src: "Ugaritic corpus", note: "god ('ilu → i-lu)" },
  { w: "ba-ru",          src: "Ugaritic corpus", note: "lord/Baal (ba'lu)" },
  { w: "ma-ru-ku",       src: "Ugaritic corpus", note: "king (malku)" },
  { w: "sa-ru",          src: "Akkadian corpus",  note: "king (šarru)" },
  { w: "a-bu",           src: "Ugaritic corpus", note: "father ('abbu)" },
  { w: "u-mu",           src: "Ugaritic corpus", note: "mother ('ummu)" },
  { w: "a-hu",           src: "Ugaritic corpus", note: "brother ('aḫu)" },
  { w: "bi-ni-tu",       src: "Ugaritic corpus", note: "daughter (bintu)" },
  { w: "ka-ru-bu",       src: "Ugaritic corpus", note: "dog (kalbu)" },
  { w: "be-tu",          src: "Ugaritic corpus", note: "house (bētu)" },
  { w: "sa-mu-su",       src: "Ugaritic corpus", note: "sun (šamšu)" },
  { w: "ya-ri-hu",       src: "Ugaritic corpus", note: "moon (yarḫu)" },
  { w: "ya-mu",          src: "Ugaritic corpus", note: "sea (yammu)" },
  { w: "a-ri-su",        src: "Ugaritic corpus", note: "earth ('arṣu)" },
  { w: "mo-tu",          src: "Ugaritic corpus", note: "death (môtu)" },
  { w: "na-ru",          src: "Akkadian corpus",  note: "river (nāru)" },
  { w: "ma-tu",          src: "Akkadian corpus",  note: "land (mātu)" },
  { w: "sa-mu-nu",       src: "Ugaritic corpus", note: "oil (šamnu)" },
  { w: "ka-ri-mu",       src: "Ugaritic corpus", note: "vineyard (karmu)" },
  { w: "da-ya-nu",       src: "Akkadian corpus",  note: "judge (dayānu)" },
  { w: "hu-ra-su",       src: "Akkadian corpus",  note: "gold (ḫurāṣu)" },
  { w: "ka-sa-pu",       src: "Akkadian corpus",  note: "silver (kaspu)" },
  { w: "ri-bu",          src: "Ugaritic corpus", note: "heart (libbu)" },
  { w: "na-pa-su",       src: "Ugaritic corpus", note: "soul (napšu)" },
  { w: "sa-ra-mu",       src: "Ugaritic corpus", note: "peace (šalāmu)" },
  { w: "da-mu",          src: "Ugaritic corpus", note: "blood (damu)" },
  { w: "mi-tu",          src: "Ugaritic corpus", note: "dead (mītu)" },
  { w: "ka-ta-ba",       src: "Ugaritic corpus", note: "he wrote (kataba)" },
  { w: "sa-ma-a",        src: "Ugaritic corpus", note: "he heard (šama'a)" },
  { w: "qa-ta-ra",       src: "Ugaritic corpus", note: "he killed (qaṭala)" },
  { w: "ma-ra-ka",       src: "Ugaritic corpus", note: "he ruled (malaka)" },
  { w: "na-ka-sa",       src: "Ugaritic corpus", note: "he cut (nakasa)" },
  { w: "ra-pa-a",        src: "Ugaritic corpus", note: "he healed (rapā'a)" },
  { w: "ha-ra-ka",       src: "Ugaritic corpus", note: "he went (halaka)" },
  { w: "da-ba-ra",       src: "Ugaritic corpus", note: "he spoke (dabara)" },
  { w: "pa-qa-da",       src: "Akkadian corpus",  note: "he appointed (paqādu)" },
  { w: "na-da-na",       src: "Akkadian corpus",  note: "he gave (nadānu)" },
  { w: "sa-ka-nu",       src: "Akkadian corpus",  note: "he placed (šakānu)" },
  { w: "ya-ka-tu-bu",    src: "Ugaritic corpus", note: "he writes (yaktub-)" },
  { w: "ya-ma-ru-ku",    src: "Ugaritic corpus", note: "he rules (yamluk-)" },
  { w: "ya-sa-ma-u",     src: "Ugaritic corpus", note: "he hears (yašma'-)" },
  { w: "ka-pu-ta-ru",    src: "Ugaritic/Akkadian", note: "Crete (Kaptaru)" },
  { w: "a-ra-si-ya",     src: "Ugaritic corpus", note: "Cyprus (Alashiya)" },
  { w: "u-ga-ri-ti",     src: "Ugaritic corpus", note: "Ugarit" },
  { w: "si-du-nu",       src: "Akkadian corpus",  note: "Sidon" },
  { w: "a-na",           src: "Akkadian/Ugaritic", note: "to/for (ana)" },
  { w: "i-na",           src: "Akkadian corpus",  note: "in (ina)" },
  { w: "a-na-ku",        src: "Ugaritic corpus", note: "I (anāku)" },
  { w: "a-ta",           src: "Ugaritic corpus", note: "you masc. ('atta)" },
  { w: "hu-a",           src: "Ugaritic corpus", note: "he (hu'a)" },
  { w: "ba-a-ru",        src: "Ugaritic corpus", note: "Baal (ba'lu) - lord" },
  { w: "a-sa-ra-tu",     src: "Ugaritic corpus", note: "Asherah ('Ašeratu)" },
  { w: "a-na-tu",        src: "Ugaritic corpus", note: "Anat ('Anatu)" },
  { w: "da-ga-nu",       src: "Ugaritic corpus", note: "Dagan" },
  { w: "qu-du-su",       src: "Ugaritic corpus", note: "holy (qudšu)" },
  { w: "bi-tu-i-ri",     src: "Ugaritic corpus", note: "temple (bīt 'ili)" },
  { w: "za-ba-hu",       src: "Ugaritic corpus", note: "sacrifice (zabaḫu)" },
  { w: "ra-bu",          src: "Ugaritic corpus", note: "great (rabbu)" },
  { w: "ta-bu",          src: "Ugaritic corpus", note: "good (ṭābu)" },
  { w: "da-nu",          src: "Ugaritic corpus", note: "strong (dannu)" },
];

export const PFU_WORDS = [
  { w: "we-te", note: "water (*wete)" },
  { w: "tu-re", note: "fire (*tule)" },
  { w: "ka-ra", note: "fish (*kala)" },
  { w: "ko-ta", note: "house (*kota)" },
  { w: "ni-mi", note: "name (*nimi)" },
  { w: "si-ma", note: "eye (*śilmä)" },
  { w: "we-re", note: "blood (*were)" },
  { w: "ru-wi", note: "bone (*luwi)" },
  { w: "me-ne", note: "go (*mene-)" },
  { w: "to-we", note: "do/make (*towe-)" },
  { w: "ko-re", note: "die (*kole-)" },
  { w: "se-we", note: "eat (*sewe-)" },
  { w: "ju-ke", note: "drink (*juke-)" },
  { w: "na-ke", note: "see (*näke-)" },
  { w: "ku-re", note: "hear (*kule-)" },
  { w: "tu-ta", note: "know (*tunta-)" },
  { w: "mi-na", note: "I (*minä)" },
  { w: "ti-na", note: "you (*tinä)" },
  { w: "pa-wa", note: "day/sun (*päjwä)" },
  { w: "ku-ne", note: "moon (*kuŋe)" },
  { w: "pu-we", note: "tree (*puwe)" },
  { w: "ki-wi", note: "stone (*kiwi)" },
  { w: "ku-te", note: "smoke (*kunte)" },
  { w: "jo-ke", note: "river (*jokV)" },
  { w: "ka-la", note: "tongue (*kälä)" },
  { w: "wa-me", note: "marrow (*wajme)" },
  { w: "pa-ta", note: "pot (*pata)" },
  { w: "su-ka", note: "fox (*śuka)" },
  { w: "ko-je", note: "husband (*kojV)" },
  { w: "pe-se", note: "nest (*pesä)" },
  { w: "no-ra", note: "arrow (*ńolV)" },
  { w: "ku-si", note: "urine (*küsV)" },
  { w: "tu-ri", note: "wind (*tulV)" },
  { w: "pe-ra", note: "fear (*pelV-)" },
  { w: "sa-ra", note: "steal (*sala)" },
  { w: "wa-ri", note: "many (*wälV)" },
  { w: "ka-ta", note: "two (*kakta)" },
  { w: "ko-me", note: "three (*kolme)" },
  { w: "ne-la", note: "four (*neljä)" },
  { w: "wi-te", note: "five (*witte)" },
  { w: "me-sa", note: "forest (*meksä)" },
  { w: "nu-mi", note: "upper (*numV)" },
  { w: "a-ra", note: "lower (*ala)" },
  { w: "pe-ri", note: "half (*pelV)" },
  { w: "sa-ka", note: "back (*sälkä)" },
  { w: "pu-na", note: "hair (*puna)" },
  { w: "mu-na", note: "egg (*muna)" },
  { w: "su-ri", note: "horn (*śorwa)" },
  { w: "wa-ta", note: "path (*wajta)" },
  { w: "ku-ta", note: "weave (*kotV-)" },
];

export const EGYPTIAN_WORDS = [
  { w: "pa-ru", note: "house (pr)" },
  { w: "me-wu", note: "water (mw)" },
  { w: "ri-a", note: "sun/Ra (rꜥ)" },
  { w: "ne-te-re", note: "god (nṯr)" },
  { w: "ne-su", note: "king (nsw)" },
  { w: "ta", note: "land (tꜣ)" },
  { w: "i-re-ti", note: "eye (jr.t)" },
  { w: "ra", note: "mouth (rꜣ)" },
  { w: "se-ti", note: "woman (s.t)" },
  { w: "i-te", note: "father (jt)" },
  { w: "me-we-ti", note: "mother (mw.t)" },
  { w: "se-me", note: "go (šm)" },
  { w: "re-di", note: "give (rdj)" },
  { w: "ma-a", note: "see (mꜣꜣ)" },
  { w: "se-de-me", note: "hear (sḏm)" },
  { w: "de-de", note: "speak (ḏd)" },
  { w: "we-ne-me", note: "eat (wnm)" },
  { w: "se-we-re", note: "drink (swr)" },
  { w: "a-ne-hu", note: "life (ꜥnḫ)" },
  { w: "he-we-ti", note: "temple (ḥw.t)" },
  { w: "he-te-pu", note: "offering (ḥtp)" },
  { w: "ke-pe-ti-u", note: "Keftiu/Crete (kftjw)" },
  { w: "we-he-me", note: "repeat (wḥm)" },
  { w: "i-me-nu", note: "Amun (jmn)" },
  { w: "ne-bu", note: "lord (nb)" },
  { w: "he-qa", note: "ruler (ḥqꜣ)" },
  { w: "i-bu", note: "heart (jb)" },
  { w: "he-pe-re", note: "become (ḫpr)" },
  { w: "ne-pe-re", note: "good (nfr)" },
  { w: "me-nu", note: "endure (mn)" },
  { w: "me-ri", note: "beloved (mry)" },
  { w: "se-nu", note: "brother (sn)" },
  { w: "se-ne-ti", note: "sister (sn.t)" },
  { w: "me-su", note: "offspring (msw)" },
  { w: "ha-se-ti", note: "foreign land (ḫꜣs.t)" },
  { w: "wa-se-ti", note: "Thebes (wꜣs.t)" },
  { w: "he-pe-su", note: "sword (ḫpš)" },
  { w: "ha-bu", note: "festival (ḥꜣb)" },
  { w: "ke-mu", note: "black (km)" },
  { w: "he-me-ti", note: "wife (ḥm.t)" },
  { w: "se-me-su", note: "follower (šmsw)" },
  { w: "i-mi", note: "who is in (jmy)" },
  { w: "we-se-re", note: "powerful (wsr)" },
  { w: "he-re", note: "face (ḥr)" },
  { w: "te-pu", note: "head (tp)" },
  { w: "pe-re-a", note: "pharaoh (pr-ꜥꜣ)" },
  { w: "re-ne-pe-ti", note: "year (rnp.t)" },
  { w: "de-se-re-ti", note: "red land (dšr.t)" },
  { w: "se-he-te-pu", note: "satisfy (sḥtp)" },
  { w: "me-re-ka-re", note: "pharaoh Merikare" },
];

export const HURRIAN_WORDS = [
  { w: "e-wu-ri", note: "king (ewri)" },
  { w: "e-ni", note: "god/lord (eni)" },
  { w: "ta-he", note: "man (tahe)" },
  { w: "a-su-ti", note: "woman (ašti)" },
  { w: "sa-ri", note: "daughter (šali)" },
  { w: "pa-hi", note: "head (pahi)" },
  { w: "su-mu-ni", note: "hand (šumuni)" },
  { w: "pa-si", note: "mouth (faši)" },
  { w: "si-hi", note: "eye (šihi)" },
  { w: "nu-hi", note: "ear (nuhi)" },
  { w: "se-ri", note: "tooth (šeri)" },
  { w: "ti-sa", note: "heart (tiša)" },
  { w: "si-je", note: "water (šiye)" },
  { w: "ta-ri", note: "fire (tari)" },
  { w: "e-se", note: "earth (eše)" },
  { w: "i-se-na", note: "rain (išena)" },
  { w: "si-mi-ki", note: "sun god (Šimigi)" },
  { w: "ku-su-hu", note: "moon god (Kušuḫ)" },
  { w: "ta-ri", note: "tree (tali)" },
  { w: "e-ra-di", note: "bird (eradi)" },
  { w: "e-ru-wi", note: "dog (erwi)" },
  { w: "pa-ba-ni", note: "mountain (pabani)" },
  { w: "ha-ri", note: "road (hari)" },
  { w: "ti-je", note: "word/name (tiye)" },
  { w: "su-ki", note: "one (šukki)" },
  { w: "si-ni", note: "two (šini)" },
  { w: "te-su-bu", note: "Teššub (storm god)" },
  { w: "he-ba-ti", note: "Ḫebat (goddess)" },
  { w: "sa-u-su-ka", note: "Šauška (Ishtar)" },
  { w: "ku-ma-ri-bi", note: "Kumarbi (god)" },
  { w: "i-te", note: "go (itte-)" },
  { w: "u-nu", note: "come (unnu-)" },
  { w: "a-ru", note: "give (ar-)" },
  { w: "a-su", note: "eat (ašu-)" },
  { w: "ha-su", note: "hear (ḫaš-)" },
  { w: "pa-ru", note: "know (pal-)" },
  { w: "pu-ru", note: "see (fur-)" },
  { w: "na-hu", note: "sit (naḫḫ-)" },
  { w: "ta-di", note: "love (tadi)" },
  { w: "sa-ri", note: "wish (šarri)" },
  { w: "pu-ri", note: "slave (puri)" },
  { w: "ti-we", note: "word (tive)" },
  { w: "u-ne", note: "land (unne)" },
  { w: "ke-ru-di", note: "health (keldi)" },
  { w: "se-na", note: "brother (šena)" },
  { w: "ne-ra", note: "water (nera)" },
  { w: "hu-ra-di", note: "warrior (ḫuradi)" },
  { w: "tu-pu-sa-ri", note: "scribe (tupšarri)" },
  { w: "a-su-hu-si", note: "horse trainer (aššuši)" },
  { w: "ki-re-na-su", note: "release (kirenašš-)" },
];

export const ETRUSCAN_WORDS = [
  { w: "ka-ra-nu", note: "son (clan)" },
  { w: "se-ku", note: "daughter (sec/seχ)" },
  { w: "pu-i-a", note: "wife (puia)" },
  { w: "a-ti", note: "mother (ati)" },
  { w: "a-pa", note: "father (apa)" },
  { w: "a-i-su", note: "god (ais/eis)" },
  { w: "su-pu-ru", note: "city (spur)" },
  { w: "zi-ra-tu", note: "magistrate (zilath)" },
  { w: "ra-u-ku-mu", note: "king (lauchum)" },
  { w: "tu-ru-ke", note: "gave (turce)" },
  { w: "mu-ru-wa-ni-ke", note: "dedicated (muluvanice)" },
  { w: "a-wi-ru", note: "year (avil)" },
  { w: "ru-pu", note: "died (lupu)" },
  { w: "pe-re-re", note: "divinity (flere)" },
  { w: "pa-nu", note: "sacred place (fanu)" },
  { w: "ka-ru", note: "dog (cal)" },
  { w: "ku-pe", note: "cup (cupe)" },
  { w: "a-tu-re", note: "building (athre)" },
  { w: "mi", note: "I (mi)" },
  { w: "mi-ni", note: "me (mini)" },
  { w: "ne-tu-nu-su", note: "Neptune (nethuns)" },
  { w: "ti-ni-a", note: "Jupiter (tinia)" },
  { w: "u-ni", note: "Juno (uni)" },
  { w: "ra-sa", note: "goddess (lasa)" },
  { w: "tu-ra-nu", note: "Venus (turan)" },
  { w: "su-ti", note: "tomb (šuθi)" },
  { w: "ra-su-na", note: "Etruscan people (rasna)" },
  { w: "tu-ra-ru", note: "boundary (tular)" },
  { w: "ru-wa", note: "brother? (ruva)" },
  { w: "me-tu-ru-mu", note: "district (methlum)" },
  { w: "e-te-ra", note: "slave/foreigner (etera)" },
  { w: "ra-u-ti-ni", note: "freedman (lautni)" },
  { w: "ku-re-na-ru", note: "sons (clenar)" },
  { w: "he-ku", note: "put/place (hec-)" },
  { w: "ma-ru", note: "look/guard (mal-)" },
  { w: "ki", note: "three (ci)" },
  { w: "ma-ku", note: "five (mach)" },
  { w: "ke-zu-pu", note: "eight (cezp)" },
  { w: "sa-ru", note: "ten (šar)" },
  { w: "he-ro-ke", note: "Lemnian: built (heloke)" },
  { w: "si-a-ri", note: "Lemnian: (sialχ-)" },
  { w: "ho-ra-i-su", note: "Lemnian: name (Holaies)" },
  { w: "na-po-ti-su", note: "Lemnian: name (Naphoth)" },
  { w: "a-ke-ru", note: "Lemnian: (aker)" },
];

export const HITTITE_WORDS = [
  { w: "pa-i", note: "to walk, to go" },
  { w: "wa-ta-ra", note: "water" },
  { w: "ne-pi-sa", note: "sky, heaven" },
  { w: "ha-sa", note: "now (adverb)" },
  { w: "ku-sa", note: "shield, leather" },
  { w: "ti-ta", note: "breast" },
  { w: "ki-sa-ra", note: "hand" },
  { w: "ta-ru", note: "forest, wood" },
  { w: "ar-is", note: "bow" },
  { w: "ma-la", note: "to grind" },
  { w: "tu-wa", note: "two" },
  { w: "su-wa-i", note: "to fill" },
  { w: "la-wa-ra", note: "to break" },
  { w: "a-te-su", note: "axe" },
  { w: "sa-li", note: "tall, post" },
  { w: "he-ku-ra", note: "mountain sanctuary" },
  { w: "wi-wa-na", note: "wine" },
  { w: "na-ta", note: "drinking straw" },
  { w: "ja-la", note: "spring, abundance" },
  { w: "pa-ra-a", note: "forth, forward" },
  { w: "ku-e-na", note: "to kill, strike" },
  { w: "ha-lu-ka", note: "message" },
  { w: "is-ha", note: "commander" },
  { w: "pu-la", note: "child" },
  { w: "wa-na", note: "woman" },
  { w: "zi-nu", note: "to present" },
  { w: "ti-ja", note: "to approach, begin" },
  { w: "ti-sa", note: "to speak" },
  { w: "it-ma-ri", note: "sacrificial dish" },
  { w: "ha-na-u-su", note: "sedan chair" },
  { w: "ta-wa-la", note: "cult beverage" },
  { w: "se-pi-ta", note: "ear of corn" },
  { w: "si-ja", note: "to seal up" },
  { w: "ap-pa", note: "prisoner, then" },
  { w: "li-ha", note: "to pour" },
  { w: "we-te", note: "to build" },
  { w: "ru-ta", note: "caterpillar" },
  { w: "ka-ka", note: "bird sound" },
  { w: "i-pa-ra", note: "oracle bird" },
  { w: "pi-su", note: "fish" },
  { w: "su-ha", note: "to spread" },
  { w: "lu-e-sa", note: "incense wood" },
  { w: "mi-a-u", note: "cat (sound)" },
  { w: "wa-la", note: "leg (Rasmussen 2017 transliteration; Linear-B-style uses `wa-`, not `va-`)" },
  { w: "ke-ri-ja", note: "to cover" },
  { w: "sa-ra-hu-li", note: "post, column" },
  { w: "ha-ra", note: "to grind (variant)" },
  { w: "i-ja-ta", note: "sheep" },
  { w: "ha-ta-la", note: "club, to strike" },
  { w: "pa-ru-na", note: "rock" },
];

export const HOMOMORPH_SET = [
  { pd: 12, ab: 78, val: "QE", conf: "high" },
  { pd: 19, ab: 31, val: "SA", conf: "high" },
  { pd: 29, ab: 80, val: "MA", conf: "high" },
  { pd: 31, ab: 81, val: "KU", conf: "high" },
  { pd: 7,  ab: 37, val: "TI", conf: "medium" },
  { pd: 18, ab: 37, val: "TI", conf: "medium" },
  { pd: 10, ab: 79, val: "ZU", conf: "medium" },
  { pd: 21, ab: 64, val: "SWI", conf: "medium-high" },
  { pd: 26, ab: 76, val: "RA2", conf: "medium" },
  { pd: 33, ab: 31, val: "SA", conf: "medium" },
  { pd: 35, ab: 4,  val: "TE", conf: "medium" },
  { pd: 39, ab: 28, val: "I",  conf: "medium" },
  { pd: 44, ab: 7,  val: "DI", conf: "medium" },
  { pd: 45, ab: 76, val: "RA2", conf: "medium" },
  { pd: 9,  ab: 301, val: "PE", conf: "medium" },
  { pd: 8,  ab: 52, val: "NO", conf: "low-medium" },
  { pd: 23, ab: 6,  val: "NA", conf: "low-medium" },
  { pd: 28, ab: 27, val: "RE", conf: "low-medium" },
  { pd: 34, ab: 39, val: "PI", conf: "low-medium" },
  { pd: 36, ab: 30, val: "NI", conf: "low-medium" },
  { pd: 37, ab: 69, val: "TU", conf: "low-medium" },
  { pd: 38, ab: 77, val: "KA", conf: "low-medium" },
  { pd: 43, ab: 66, val: "TJA", conf: "low-medium" },
];

export const LINEAR_A_EXCLUDED = [
  { w: "a-mi-ni-so",   src: "KN Fp+",   note: "Amnisos — Cretan place name" },
  { w: "ko-no-so",     src: "KN",        note: "Knossos — Cretan place name" },
  { w: "pa-i-to",      src: "KN",        note: "Phaistos — Cretan place name" },
  { w: "su-ki-ri-ta",  src: "KN Db+",    note: "Sukrita — Cretan place name" },
  { w: "ma-di-na",     src: "HT 97a",    note: "personal name or toponym" },
  { w: "da-we-da",     src: "ZA 10b",    note: "personal name or toponym" },
  { w: "wi-ri-no",     src: "HT 117a",   note: "wool/flax? — probable Greek cognate" },
  { w: "e-ka-ra",      src: "HT Wc 3017",note: "fireplace? — probable Greek cognate" },
  { w: "te-me-no",     src: "PK Za 11",  note: "shrine — Greek borrowing (τέμενος)" },
  { w: "na-wi-jo",     src: "HT 6a",     note: "nautical term? — probable Greek cognate" },
  { w: "qe-to",        src: "HT 86a",    note: "toponym?" },
  { w: "de-mi-ni-ja",  src: "KH 5.1",    note: "personal/divine name?" },
  { w: "ta-ra-nu",     src: "KN Zf 31",  note: "footstool — probable Greek cognate (θρᾶνυς)" },
  { w: "a-ke-ti-rja",  src: "PK Za 11",  note: "cf. Linear B a-ke-ti-ri-ja (ἀσκήτριαι)" },
  { w: "a-sa-ta-tja",  src: "PK Za 11",  note: "uncertain interpretation" },
];

export const LINEAR_A_FULL = [...LINEAR_A_WORDS, ...LINEAR_A_EXCLUDED];

export const LA_TEXTS = [
  "a-ta-i-*301-wa-ja",
  "ja-di-ki-tu",
  "ja-sa-sa-ra-me",
  "u-na-ka-na-si",
  "i-pi-na-ma",
  "si-ru-te",
  "ta-na-ra-te",
  "u-ti-nu",
  "i-*301-wa-ja",
  "i-*301-wa-e",
  "da-pi-te-ri",
  "a-di-ki-te-te",
  "tu-me-i",
  "u-na-ru-ka-na-ti",
  "ma-te-re-sa",
  "ti-di-te",
  "ti-di-te-qa-ti",
  "ma-ka-ri-te",
  "na-da-re",
  "da-ru-ne-te",
  "ka-ku-ne-te",
  "ku-ro",
  "ki-ro",
  "qe-ku-re",
  "ti-ti-ku",
  "pi-rju-te",
  "ja-sa-ja",
  "ja-si-e",
  "i-da-ma-na",
  "si-da-te",
  "ku-ra",
  "sa-sa-ma",
  "ku-mi-no",
  "a-sa-sa-ra-ma-na",
  "a-mi-ni-so",
  "ko-no-so",
  "pa-i-to",
  "su-ki-ri-ta",
  "ma-di-na",
  "da-we-da",
  "wi-ri-no",
  "e-ka-ra",
  "te-me-no",
  "na-wi-jo",
  "qe-to",
  "de-mi-ni-ja",
  "ta-ra-nu",
  "a-ke-ti-rja",
  "a-sa-ta-tja",
];

export const LANGUAGES = [
  { id: "minoan", name: "Minoan / Linear A", words: LINEAR_A_WORDS },
  { id: "greek", name: "Mycenaean Greek", words: GREEK_WORDS },
  { id: "luwian", name: "Luwian (Anatolian)", words: LUWIAN_WORDS },
  { id: "semitic", name: "West Semitic", words: SEMITIC_WORDS },
  { id: "pfu", name: "Proto-Finno-Ugric", words: PFU_WORDS },
  { id: "egyptian", name: "Middle Egyptian", words: EGYPTIAN_WORDS },
  { id: "hurrian", name: "Hurrian", words: HURRIAN_WORDS },
  { id: "etruscan", name: "Etruscan/Tyrsenian", words: ETRUSCAN_WORDS },
];
