import { el, table, resultCard, progressBar } from "../dom.mjs";
import { createBarChart, destroyChart } from "../charts.mjs";

// Canonical output: 100k iterations, seeds 314159+i (uniform) / 271828+i (freq-weighted)
// Generated by: node scripts/generate-canonical-values.mjs
// Mirrored from canonical-values.json; verify-canonical imports this constant
// directly to guard drift (no regex over prose).
export const PRE_COMPUTED = [
  { id: "minoan", name: "Minoan / Linear A", corpusSize: 34, effectiveSize: 34, overlap: 9, pValue: 0.0318, fwPValue: 0.7061, holmP: 0.2858, hyperP: 0.0022 },
  { id: "hittite", name: "Hittite (Rasmussen)", corpusSize: 50, effectiveSize: 50, overlap: 8, pValue: 0.1012, fwPValue: 0.8953, holmP: 0.8098, hyperP: 0.0118 },
  { id: "luwian", name: "Luwian (Anatolian)", corpusSize: 72, effectiveSize: 71, overlap: 8, pValue: 0.1765, fwPValue: 0.9988, holmP: 1.0000, hyperP: 0.0255 },
  { id: "greek", name: "Mycenaean Greek", corpusSize: 67, effectiveSize: 67, overlap: 4, pValue: 0.6362, fwPValue: 0.9058, holmP: 1.0000, hyperP: 0.3221 },
  { id: "pfu", name: "Proto-Finno-Ugric", corpusSize: 50, effectiveSize: 50, overlap: 2, pValue: 0.7188, fwPValue: 0.9037, holmP: 1.0000, hyperP: 0.4936 },
  { id: "hurrian", name: "Hurrian", corpusSize: 50, effectiveSize: 50, overlap: 2, pValue: 0.8102, fwPValue: 0.9751, holmP: 1.0000, hyperP: 0.5981 },
  { id: "semitic", name: "West Semitic", corpusSize: 60, effectiveSize: 60, overlap: 1, pValue: 0.9880, fwPValue: 1.0000, holmP: 1.0000, hyperP: 0.9495 },
  { id: "egyptian", name: "Middle Egyptian", corpusSize: 50, effectiveSize: 48, overlap: 0, pValue: 1.0000, fwPValue: 1.0000, holmP: 1.0000, hyperP: 1.0000 },
  { id: "etruscan", name: "Etruscan/Tyrsenian", corpusSize: 44, effectiveSize: 42, overlap: 0, pValue: 1.0000, fwPValue: 1.0000, holmP: 1.0000, hyperP: 1.0000 },
];

function formatP(p) {
  // Guard against NaN / Infinity / non-numeric inputs so an engine bug
  // surfaces as an obvious "n/a" cell rather than a silent "NaN" string.
  if (!Number.isFinite(p)) return "n/a";
  if (p >= 1) return "1.0000";
  return p.toFixed(4);
}

function buildTable(results) {
  const headers = ["Rank", "Language", "Corpus", "Overlap", "MC p", "FW p", "Holm p", "HG p", "Uniform MC < 0.05", "Holm < 0.05"];
  const rows = results.map((r, i) => {
    const rawSig = r.pValue < 0.05;
    const holmSig = r.holmP < 0.05;
    const rawCell = el("span", { className: rawSig ? "sig" : "not-sig" }, rawSig ? "yes" : "no");
    const holmCell = el("span", { className: holmSig ? "sig" : "not-sig" }, holmSig ? "yes" : "no");
    return [
      i + 1,
      r.name,
      r.effectiveSize != null ? `${r.corpusSize} (${r.effectiveSize})` : r.corpusSize,
      r.overlap,
      { value: formatP(r.pValue), className: "mono" + (rawSig ? " sig" : "") },
      { value: formatP(r.fwPValue), className: "mono" },
      { value: formatP(r.holmP), className: "mono" + (holmSig ? " sig" : "") },
      { value: formatP(r.hyperP), className: "mono" },
      rawCell,
      holmCell,
    ];
  });
  return table(headers, rows);
}

function corpusSizeFootnoteEl() {
  return el("p", { className: "text-hint" },
    "Corpus = total words (effective). Effective count excludes single-syllable words ",
    "(e.g. \u201Cda\u201D, \u201Cta\u201D) which produce zero bigrams and do not contribute to overlap.");
}

function buildChart(canvas, results) {
  const labels = results.map(r => r.name);
  const pvals = results.map(r => r.pValue);
  const fwPvals = results.map(r => r.fwPValue);

  return createBarChart(canvas, {
    labels,
    datasets: [
      {
        label: "Uniform MC p-value",
        data: pvals,
        backgroundColor: pvals.map(p => p < 0.05 ? "#2e7d32" : "#b71c1c"),
        borderWidth: 1,
      },
      {
        label: "Freq-weighted MC p-value",
        data: fwPvals,
        backgroundColor: fwPvals.map(() => "#ff8a65"),
        borderWidth: 1,
      },
    ],
    title: "Nine-Language Comparison: MC p-Values",
    yLabel: "p-value",
    xLabel: "Language hypothesis",
    yMax: 1.05,
    threshold: 0.05,
  });
}

function buildVerdictEl(results, iters) {
  const minoan = results.find(r => r.id === "minoan");
  if (!minoan) return el("span", {}, "No Minoan result available.");
  const sigCount = results.filter(r => r.pValue < 0.05).length;
  const label = iters ? `(${(iters / 1000).toFixed(0)}k iterations)` : "(canonical 100k)";
  if (sigCount === 1 && minoan.pValue < 0.05) {
    return el("span", {},
      `Minoan/Linear A is the only language below \u03B1 = 0.05 under the uniform null `,
      `(p = ${formatP(minoan.pValue)}), but does not survive Holm-Bonferroni correction `,
      `(Holm p = ${formatP(minoan.holmP)}) or the frequency-weighted null `,
      `(FW p = ${formatP(minoan.fwPValue)}). ${label}`);
  }
  if (sigCount === 0) {
    return el("span", {},
      `No language reaches \u03B1 = 0.05 under the uniform null. `,
      `Minoan/Linear A is the closest (p = ${formatP(minoan.pValue)}). ${label}`);
  }
  return el("span", {},
    `${sigCount} language(s) below \u03B1 = 0.05. `,
    `Minoan p = ${formatP(minoan.pValue)}, Holm p = ${formatP(minoan.holmP)}. ${label}`);
}

export function render(container, ctx) {
  let chartInstance = null;
  let worker = null;

  const tableContainer = el("div", { id: "comparison-table" });
  tableContainer.appendChild(buildTable(PRE_COMPUTED));
  tableContainer.appendChild(corpusSizeFootnoteEl());

  const canvas = el("canvas", {
    width: "800",
    height: "400",
    role: "img",
    "aria-label": "Bar chart comparing MC p-values across nine ancient languages",
  }, "Bar chart of nine-language comparison p-values. Data also available in the table above.");
  const chartContainer = el("div", { className: "chart-container" }, canvas);

  const verdictEl = el("div", { className: "key-finding" },
    el("strong", {}, "Result: "),
    buildVerdictEl(PRE_COMPUTED, null));

  const statusEl = el("p", { className: "loading" });
  const progressEl = el("div");

  const runBtn = el("button", {
    className: "btn-run",
    onClick() {
      runBtn.disabled = true;
      runBtn.setAttribute("aria-busy", "true");
      statusEl.textContent = "Starting Monte Carlo simulation...";

      const iterations = ctx.getIterations();
      worker = new Worker("dist/mc-worker.bundle.js");

      worker.onerror = (err) => {
        statusEl.textContent = `Error: ${err.message || "Worker failed"}`;
        runBtn.disabled = false;
        runBtn.setAttribute("aria-busy", "false");
        progressEl.replaceChildren();
        worker.terminate();
        worker = null;
      };

      worker.onmessage = (e) => {
        if (e.data.type === "error") {
          statusEl.textContent = `Error: ${e.data.message || "Worker failed"}`;
          runBtn.disabled = false;
          runBtn.setAttribute("aria-busy", "false");
          progressEl.replaceChildren();
          worker.terminate();
          worker = null;
          return;
        }
        if (e.data.type === "progress") {
          const { done, total, lang } = e.data;
          statusEl.textContent = `Computing ${lang}... (${done}/${total})`;
          progressEl.replaceChildren(progressBar(done / total));
        }

        if (e.data.type === "result") {
          const { results, iterations: iters } = e.data;
          const minoan = results.find(r => r.id === "minoan");
          const preMinoan = PRE_COMPUTED.find(r => r.id === "minoan");
          if (minoan && preMinoan && minoan.overlap !== preMinoan.overlap) {
            statusEl.textContent += ` \u26A0 Minoan overlap (${minoan.overlap}) differs from pre-computed (${preMinoan.overlap}). Data may have changed.`;
          }

          tableContainer.replaceChildren(buildTable(results), corpusSizeFootnoteEl());

          if (chartInstance) destroyChart(chartInstance);
          const newCanvas = el("canvas", {
            width: "800",
            height: "400",
            role: "img",
            "aria-label": "Bar chart comparing MC p-values across nine ancient languages",
          });
          chartContainer.replaceChildren(newCanvas);
          chartInstance = buildChart(newCanvas, results);

          verdictEl.replaceChildren(
            el("strong", {}, "Result: "),
            buildVerdictEl(results, iters));

          const msg = `Completed ${iters.toLocaleString()} iterations per language.`;
          statusEl.textContent = msg;
          ctx.announce(msg);
          progressEl.replaceChildren();
          runBtn.disabled = false;
          runBtn.setAttribute("aria-busy", "false");
          worker.terminate();
          worker = null;
        }
      };

      worker.postMessage({ type: "run-comparison", iterations });
    },
  }, "Run Monte Carlo");

  container.appendChild(
    el("div", {},
      el("h2", {}, "Nine-Language Comparison"),

      el("p", {},
        "This is the core analysis: the disc\u2019s phonetic reading is compared against ",
        "reference vocabularies from nine ancient languages using bigram overlap as a ",
        "similarity metric. Languages are ranked by Monte Carlo p-value (lower = more ",
        "similar to the disc)."
      ),

      el("p", {},
        "Three null models are reported: uniform MC (primary), frequency-weighted MC ",
        "(conservative), and hypergeometric (analytical cross-check). Holm-Bonferroni ",
        "correction adjusts for nine simultaneous tests."
      ),

      el("div", { className: "result-card" },
        el("div", { className: "run-control" },
          runBtn,
          el("span", { className: "mono text-hint" },
            "Re-run with live Monte Carlo to verify results"
          )
        ),
        statusEl,
        progressEl
      ),

      verdictEl,

      el("p", { className: "text-hint" },
        "Note: Hittite (Rasmussen) uses an independent phonetic map derived from Rasmussen (2010), ",
        "not the Daidalika signary. In this reading, Sign 02 is treated phonetically as \u201Cis\u201D ",
        "(adding 19 tokens), whereas the Daidalika reading excludes it as a determinative. ",
        "Both readings use the same bigram construction pipeline. ",
        "Each language uses an independently seeded PRNG (uniformSeed + languageIndex), ",
        "so individual p-values are reproducible without running the full suite."
      ),

      el("p", { className: "text-hint" },
        "HG p-values are a cross-check only. The hypergeometric uses N = S\u00B2 (all theoretically ",
        "possible ordered bigram pairs), which exceeds the number of attested bigrams and ",
        "produces systematically smaller p-values than the MC simulation. The MC simulation is ",
        "the primary test because it generates random pseudo-disc texts through the same ",
        "word-length-preserving process, implicitly accounting for bigram producibility."
      ),

      tableContainer,
      chartContainer
    )
  );

  requestAnimationFrame(() => {
    chartInstance = buildChart(canvas, PRE_COMPUTED);
  });
}
