import { el, text } from "../dom.mjs";

export function render(container, ctx) {
  container.appendChild(
    el("div", {},
      el("h2", {}, "Methodology"),

      el("h3", {}, "Analytical Approach"),
      el("p", {},
        "This workbench implements a hypothesis-screening framework: rather than ",
        "attempting to prove the disc is written in a particular language, it asks ",
        "which language hypotheses are not supported by a single, consistent statistical ",
        "test. We deliberately do not say \u201cruled out\u201d, because a language can fail this ",
        "Daidalika-reading bigram test without being excluded under a different sign-value ",
        "system, a larger reference corpus, different transliteration rules, or a different ",
        "statistic. The approach uses bigram overlap as a language-similarity metric, comparing ",
        "the disc\u2019s phonetic reading against reference vocabularies from nine ancient languages."
      ),

      el("h3", {}, "Phonetic Values"),
      el("p", {},
        "Phonetic values are assigned to the 45 disc signs based on visual correspondences ",
        "(homomorphs) with Linear A and Linear B signs whose values are known. ",
        "This follows the methodology of Packard (and subsequent scholars). ",
        "Each assignment carries a confidence level from HIGH (e.g., signs clearly ",
        "matching well-attested Linear B values) to LOW (tentative or ambiguous matches)."
      ),

      el("h3", {}, "Bigram Overlap Method"),
      el("p", {},
        "For each candidate language, the test counts how many consecutive syllable pairs ",
        "(bigrams) in the disc\u2019s phonetic reading also appear in the reference vocabulary. ",
        "This count is compared against a null distribution generated by Monte Carlo ",
        "simulation, where random pseudo-words of the same length distribution are drawn."
      ),
      el("p", {},
        "Two null models are employed: (1) a uniform null, where syllables are sampled ",
        "uniformly from the combined syllable inventory, and (2) a frequency-weighted null, ",
        "where syllables are sampled proportionally to their frequency in the combined corpus. ",
        "The frequency-weighted null controls for the possibility that overlap is driven ",
        "by high-frequency syllables appearing in both corpora."
      ),

      el("h3", {}, "Multiple Testing Correction"),
      el("p", {},
        "Because nine languages are tested simultaneously, the Holm-Bonferroni correction ",
        "is applied to control the family-wise error rate. The corrected p-value for the ",
        "best-ranked language (Minoan) is 0.286, which does not reach significance at ",
        "\u03B1 = 0.05."
      ),

      el("h3", {}, "The Barber Limit"),
      el("p", {},
        "Barber (1974) demonstrated a mathematical constraint on decipherment verification: ",
        "with only ~240 tokens of an undeciphered script, there is insufficient text to ",
        "uniquely determine phonetic values through internal evidence alone. Any proposed ",
        "decipherment of the Phaistos Disc therefore remains inherently unverifiable ",
        "from the disc text alone, regardless of how well it fits a particular language."
      ),

      el("h3", {}, "Reproducibility"),
      el("p", {},
        "All Monte Carlo simulations use a seeded pseudorandom number generator (mulberry32) ",
        "to ensure bit-exact reproducibility across platforms. The uniform null uses seed ",
        "314159; the frequency-weighted null uses seed 271828. Results from this web ",
        "application are deterministic across runs when using the same iteration count."
      ),

      el("h3", {}, "Caveats"),
      el("div", { className: "result-card" },
        el("ul", {},
          el("li", {},
            el("strong", {}, "Reading direction: "),
            text("The disc\u2019s intended reading direction is unknown. All headline analyses use the conventional outside-in direction. "),
            text("The Extended Analysis tab exposes a within-word direction-reversal test (after stripping the Sign 02 determinative): the Minoan bigram overlap drops from 9 to 4 under reversal and the uniform-null Monte Carlo p rises above 0.6, so the headline overlap is direction-dependent rather than direction-invariant. "),
            text("A broader sensitivity sweep over word-order reversal and combined transforms is documented in the paper and lives in the research repository\u2019s CLI tools; morphological patterns have not been independently tested under reversed reading.")
          ),
          el("li", {},
            el("strong", {}, "Phonetic values: "),
            text("Assignments are hypothetical. The entire analysis is conditional on these values being at least approximately correct.")
          ),
          el("li", {},
            el("strong", {}, "Corpus limitations: "),
            text("Reference vocabularies vary in size (34\u201372 words) and may not represent the full phonological inventory of each language. "),
            text("Single-syllable words produce zero bigrams and do not contribute to overlap counts.")
          ),
          el("li", {},
            el("strong", {}, "Lacuna policy ("),
            el("code", {}, "??"),
            text(" tokens and Sign 17): "),
            text("Damaged sign impressions ("),
            el("code", {}, "??"),
            text(") and signs without an established phonetic value (notably Sign 17, recorded internally as "),
            el("code", {}, "?17"),
            text(") are treated as "),
            el("em", {}, "adjacency-breaking boundaries"),
            text(" \u2014 not as omissions and not as wildcards \u2014 in all phonetic and statistical computations. "),
            text("Concretely: the affected word is split into independent sub-segments at every unknown sign, "),
            text("bigrams are formed only within each sub-segment, and each sub-segment's length is appended separately to the Monte-Carlo word-length pool so the null model draws independent \u201cfake sub-words\u201d at the same lengths. "),
            text("This is stricter than treating lacunae as omissions (it eliminates any bigram that would span an unknown sign) and stricter than a wildcard (which would inflate the bigram set across lacunae); both alternatives are explicitly rejected. "),
            text("Counts of word groups (61) and readable sign impressions (241) reflect the surface transcription; the 52 distinct disc bigrams reflect the adjacency-breaking policy described here. "),
            text("Reading-order display strings such as "),
            el("code", {}, "de-ti-?17-sa"),
            text(" use \u201c?17\u201d as a placeholder for the unknown-value sign and are display-only; the bigram engine never sees that placeholder as a valid syllable.")
          ),
          el("li", {},
            el("strong", {}, "CV/V syllable structure: "),
            text("100% CV/V structure in the phonetic reading is a necessary consequence of using Linear B-derived values, not independent validation.")
          ),
          el("li", {},
            el("strong", {}, "Bigram method: "),
            text("This is a non-standard text categorization approach, chosen for robustness with very small corpora (cf. Cavnar & Trenkle 1994).")
          ),
          el("li", {},
            el("strong", {}, "Features not in this workbench: "),
            text("The broader directionality sweep (word-order reversal and combined transforms), Ventris-style CV grid, Packard Distribution Index, Duhoux prefix:suffix ratio test, "),
            text("and Kuykendall mutual-information replication are documented in the paper but implemented only in the research repository\u2019s CLI tools. "),
            text("The within-word direction-reversal test is exposed in the public Extended Analysis tab.")
          )
        )
      )
    )
  );
}
