import { el, resultCard, progressBar, table } from "../dom.mjs";
import { LINEAR_A_WORDS, LINEAR_A_EXCLUDED, LINEAR_A_FULL } from "../engine/data.mjs";
import { computeOverlapCount } from "../engine/comparison.mjs";

// Canonical output: 100k iterations, seeds 314159 (det) / 314160 (phon) / 314161 (sign18rju)
// Generated by: node scripts/generate-canonical-values.mjs
// Mirrored from canonical-values.json; verify-canonical imports these constants
// directly to guard drift (no regex over prose).
export const PRE_SIGN02 = {
  det:  { tokens: 241, phonSigns: 43, overlap: 9, pValue: 0.0318 },
  phon: { tokens: 241, phonSigns: 44, overlap: 9, pValue: 0.0562 },
};

export const PRE_SIGN18_RJU = { overlap: 9, pValue: 0.0307 };

export const PRE_CIRCULARITY = {
  realOverlap: 9,
  uniformP: 0.0047,
  freqWeightedP: 0.3647,
  spearmanRho: 0.257,
  tierSweep: [
    { tierCount: 2,  freqWeightedP: 0.1853, tierSizes: [22, 21] },
    { tierCount: 3,  freqWeightedP: 0.3647, tierSizes: [15, 15, 13] },
    { tierCount: 5,  freqWeightedP: 0.4377, tierSizes: [9, 9, 9, 8, 8] },
    { tierCount: 10, freqWeightedP: 0.5733, tierSizes: [5, 5, 5, 4, 4, 4, 4, 4, 4, 4] },
  ],
};

function renderSign02Card(label, data, desc) {
  return resultCard(label,
    el("p", {}, desc),
    el("p", { className: "mono" },
      `Tokens: ${data.tokens} | Phonetic signs: ${data.phonSigns} | ` +
      `Minoan overlap: ${data.overlap} | MC p = ${data.pValue.toFixed(4)}`)
  );
}

function renderSign18Card(label, overlap, pValue, desc) {
  return resultCard(label,
    el("p", {}, desc),
    el("p", { className: "mono" }, `Minoan overlap: ${overlap} | MC p = ${pValue.toFixed(4)}`)
  );
}

function renderTierSweepTable(sweep) {
  if (!Array.isArray(sweep) || sweep.length === 0) return null;
  const headers = ["Tiers (T)", "Tier sizes", "Freq-weighted p"];
  const rows = sweep.map(s => {
    const sig = s.freqWeightedP < 0.05;
    return [
      s.tierCount,
      { value: s.tierSizes.join(", "), className: "mono" },
      { value: s.freqWeightedP.toFixed(4), className: "mono" + (sig ? " sig" : "") },
    ];
  });
  return table(headers, rows);
}

function renderCircCard(circ) {
  const sweepTable = renderTierSweepTable(circ.tierSweep);
  const children = [
    el("p", { className: "mono" },
      `Real Minoan overlap: ${circ.realOverlap}`),
    el("p", { className: "mono" },
      `Uniform reshuffling p = ${circ.uniformP.toFixed(4)}`),
    el("p", { className: "mono" },
      `Freq-weighted reshuffling p (T = 3) = ${circ.freqWeightedP.toFixed(4)} ` +
      `(Spearman \u03C1 = ${circ.spearmanRho.toFixed(3)})`),
    el("p", {},
      "Uniform: reshuffles all 43 sign\u2192value assignments. " +
      "Freq-weighted: reshuffles within T frequency tiers, ",
      "preserving the macro correlation between disc sign frequency and LA syllable frequency."),
  ];
  if (sweepTable) {
    children.push(el("h4", {}, "Tier-count sensitivity sweep"));
    children.push(el("p", {},
      "The frequency-weighted p depends on the tier count T (a hyperparameter). ",
      "T = 1 reduces to the uniform null; large T approaches a fully rank-pinned shuffle. ",
      "The sweep below shows that the FW null is conservative across all tested T values, ",
      "with no value falling below \u03B1 = 0.05."));
    children.push(sweepTable);
  }
  children.push(el("p", { className: "text-hint" },
    "Note: finer tiers preserve the frequency correlation more strictly, ",
    "coarser tiers approach the uniform reshuffle. T = 3 is reported as the headline figure ",
    "for backward compatibility; the sweep is the honest reading."));
  return resultCard("Circularity Bias Control", ...children);
}

export function render(container, ctx) {
  let worker = null;

  const sign02DetCard = el("div", { id: "s02-det" });
  sign02DetCard.appendChild(renderSign02Card(
    "Default: Determinative", PRE_SIGN02.det,
    "Sign 02 treated as a non-phonetic determinative (default). Excluded from phonetic reading."
  ));

  const sign02PhonCard = el("div", { id: "s02-phon" });
  sign02PhonCard.appendChild(renderSign02Card(
    "Alternative: Phonetic", PRE_SIGN02.phon,
    "Sign 02 treated as phonetic (i). Included in bigram computation."
  ));

  const circCard = el("div", { id: "circ-result" });
  circCard.appendChild(renderCircCard(PRE_CIRCULARITY));

  const sign18TiCard = el("div", { id: "s18-ti" });
  sign18TiCard.appendChild(renderSign18Card(
    "Default: Allograph (ti)", PRE_SIGN02.det.overlap, PRE_SIGN02.det.pValue,
    "Sign 18 = ti (allograph of Sign 07). This is the default reading."
  ));

  const sign18RjuCard = el("div", { id: "s18-rju" });
  sign18RjuCard.appendChild(renderSign18Card(
    "Alternative: Distinct (rju)", PRE_SIGN18_RJU.overlap, PRE_SIGN18_RJU.pValue,
    "Sign 18 given the distinct value rju (Owens/Palmer). Changes some bigrams."
  ));

  const sign02Verdict = el("div", { className: "key-finding" },
    el("strong", {}, "Verdict: "),
    el("span", {},
      `P-value rises from ${PRE_SIGN02.det.pValue.toFixed(3)} to ${PRE_SIGN02.phon.pValue.toFixed(3)}`,
      PRE_SIGN02.phon.pValue < 0.05
        ? " \u2014 marginally below \u03B1 = 0.05. The result survives this choice, but the margin is thin. (canonical 100k)"
        : ` \u2014 above \u03B1 = 0.05. The result does NOT survive under phonetic treatment. (canonical 100k)`));

  const circVerdict = el("div", { className: "key-finding" },
    el("strong", {}, "Interpretation: "),
    el("span", {},
      "The uniform test (p \u2248 0.005) confirms the specific sign correspondences outperform random. ",
      "The frequency-weighted test (p \u2248 0.36) reveals that much of the overlap is attributable ",
      "to frequency correlation: frequent disc signs being paired with frequent LA values. ",
      "The eight language eliminations are unaffected by either control. (canonical 100k)"));

  const statusEl = el("p", { className: "loading" });
  const progressEl = el("div");

  const runBtn = el("button", {
    className: "btn-run",
    onClick() {
      runBtn.disabled = true;
      runBtn.setAttribute("aria-busy", "true");
      statusEl.textContent = "Starting sensitivity tests...";
      const iterations = ctx.getIterations();

      worker = new Worker("dist/mc-worker.bundle.js");

      worker.onerror = (err) => {
        statusEl.textContent = `Error: ${err.message || "Worker failed"}`;
        runBtn.disabled = false;
        runBtn.setAttribute("aria-busy", "false");
        progressEl.replaceChildren();
        worker.terminate();
        worker = null;
      };

      worker.onmessage = (e) => {
        if (e.data.type === "error") {
          statusEl.textContent = `Error: ${e.data.message || "Worker failed"}`;
          runBtn.disabled = false;
          runBtn.setAttribute("aria-busy", "false");
          progressEl.replaceChildren();
          worker.terminate();
          worker = null;
          return;
        }
        if (e.data.type === "progress") {
          statusEl.textContent = `${e.data.step}... (${e.data.done}/${e.data.total})`;
          progressEl.replaceChildren(progressBar(e.data.done / e.data.total));
        }

        if (e.data.type === "sensitivity-result") {
          const { sign02det, sign02phon, sign18rju, circularity, iterations: iters } = e.data;
          if (sign02det.overlap !== PRE_SIGN02.det.overlap) {
            statusEl.textContent += ` \u26A0 Overlap (${sign02det.overlap}) differs from pre-computed (${PRE_SIGN02.det.overlap}). Data may have changed.`;
          }

          sign02DetCard.replaceChildren(renderSign02Card(
            "Default: Determinative",
            { tokens: 241, phonSigns: 43, overlap: sign02det.overlap, pValue: sign02det.pValue },
            "Sign 02 treated as a non-phonetic determinative (default). Excluded from phonetic reading."
          ));
          sign02PhonCard.replaceChildren(renderSign02Card(
            "Alternative: Phonetic",
            { tokens: 241, phonSigns: 44, overlap: sign02phon.overlap, pValue: sign02phon.pValue },
            "Sign 02 treated as phonetic (i). Included in bigram computation."
          ));

          sign18TiCard.replaceChildren(renderSign18Card(
            "Default: Allograph (ti)", sign02det.overlap, sign02det.pValue,
            "Sign 18 = ti (allograph of Sign 07). This is the default reading."
          ));
          sign18RjuCard.replaceChildren(renderSign18Card(
            "Alternative: Distinct (rju)", sign18rju.overlap, sign18rju.pValue,
            "Sign 18 given the distinct value rju (Owens/Palmer). Changes some bigrams."
          ));

          circCard.replaceChildren(renderCircCard(circularity));

          const kLabel = `(${(iters / 1000).toFixed(0)}k iterations)`;
          sign02Verdict.replaceChildren(
            el("strong", {}, "Verdict: "),
            el("span", {},
              `P-value rises from ${sign02det.pValue.toFixed(3)} to ${sign02phon.pValue.toFixed(3)}`,
              sign02phon.pValue < 0.05
                ? ` \u2014 marginally below \u03B1 = 0.05. The result survives this choice, but the margin is thin. ${kLabel}`
                : ` \u2014 above \u03B1 = 0.05. The result does NOT survive under phonetic treatment. ${kLabel}`));

          circVerdict.replaceChildren(
            el("strong", {}, "Interpretation: "),
            el("span", {},
              `The uniform test (p = ${circularity.uniformP.toFixed(4)}) `,
              circularity.uniformP < 0.05 ? "confirms" : "does not confirm",
              " the specific sign correspondences outperform random. ",
              `The frequency-weighted test (p = ${circularity.freqWeightedP.toFixed(4)}) `,
              circularity.freqWeightedP > 0.05
                ? "reveals that much of the overlap is attributable to frequency correlation. "
                : "suggests the overlap goes beyond frequency correlation. ",
              `The eight language eliminations are unaffected by either control. ${kLabel}`));

          const msg = `Completed ${iters.toLocaleString()} iterations per test.`;
          statusEl.textContent = msg;
          ctx.announce(msg);
          progressEl.replaceChildren();
          runBtn.disabled = false;
          runBtn.setAttribute("aria-busy", "false");
          worker.terminate();
          worker = null;
        }
      };

      worker.postMessage({ type: "run-sensitivity", iterations });
    },
  }, "Run Sensitivity Tests");

  container.appendChild(
    el("div", {},
      el("h2", {}, "Sensitivity Analysis"),

      el("p", {},
        "These tests examine how sensitive the results are to key analytical choices. ",
        "If a small change in assumptions causes the results to flip, the finding is fragile. ",
        "All four tests below run live in the browser via Monte Carlo simulation."
      ),

      el("div", { className: "result-card" },
        el("div", { className: "run-control" },
          runBtn,
          el("span", { className: "mono text-hint" },
            "Re-run all sensitivity tests live (Sign 02, Sign 18, circularity)")
        ),
        statusEl,
        progressEl
      ),

      el("h3", {}, "Sign 02: Determinative vs. Phonetic"),
      el("p", {},
        "Sign 02 (the \u201Cplumed head\u201D sign) appears word-initially 19 times and is treated ",
        "as a non-phonetic determinative in the default reading. This test compares results ",
        "when it is included as a phonetic sign."
      ),
      sign02DetCard,
      sign02PhonCard,
      sign02Verdict,

      el("h3", {}, "Sign 18: Allograph vs. Distinct Value"),
      el("p", {},
        "Sign 18 is treated as an allograph of Sign 07 (both = \u201Cti\u201D) in the default reading. ",
        "This test checks what happens if Sign 18 is assigned the distinct phonetic value \u201Crju\u201D ",
        "(Owens/Palmer reading)."
      ),
      sign18TiCard,
      sign18RjuCard,

      el("h3", {}, "Circularity Bias Control"),
      el("p", {},
        "If the phonetic mapping simply correlates high-frequency PD signs with high-frequency ",
        "LA syllables, bigram overlap could be an artifact. Two controls test this: ",
        "uniform reshuffling (all 43 values randomized) and frequency-weighted reshuffling ",
        "(values randomized only within matching frequency tiers, preserving the macro structure)."
      ),
      circCard,
      circVerdict,

      el("h3", {}, "Allograph Merge Sensitivity"),
      el("p", {},
        "Signs 07/18 (\u201Cti\u201D), 19/33 (\u201Csa\u201D), and 26/45 (\u201Crja\u201D) are proposed allograph pairs. ",
        "Merging them reduces the sign inventory from 45 to 42 distinct signs. ",
        "The merge has negligible impact on bigram overlap because merged signs produce ",
        "the same syllable strings (\u0394p \u2248 0.000)."
      ),
      el("p", { className: "text-hint" },
        "This is an analytical argument, not a Monte Carlo simulation: since allograph pairs ",
        "share identical phonetic values, merging them cannot change any bigram in the reading. ",
        "A formal MC verification is therefore unnecessary."
      ),

      el("h3", {}, "Vocabulary Curation: 34 vs. 49 Words"),
      (() => {
        const { sideA, sideB } = ctx;
        const overlap34 = computeOverlapCount(sideA, sideB, LINEAR_A_WORDS);
        const overlap49 = computeOverlapCount(sideA, sideB, LINEAR_A_FULL);
        const delta = overlap49 - overlap34;
        return el("div", {},
          el("p", {},
            "The default comparison uses a curated 34-word Linear A corpus that excludes ",
            "Cretan place names (Knossos, Phaistos, Amnisos, Sukrita), probable Greek borrowings ",
            "(te-me-no, ta-ra-nu, e-ka-ra, wi-ri-no, na-wi-jo, a-ke-ti-rja), ",
            "and items of uncertain provenance. ",
            "This test checks whether including the full 49-word set changes the overlap."
          ),
          resultCard("34-word corpus (default)",
            el("p", { className: "mono" },
              `Minoan bigram overlap: ${overlap34}`)
          ),
          resultCard("49-word corpus (full)",
            el("p", { className: "mono" },
              `Minoan bigram overlap: ${overlap49} (\u0394 = ${delta >= 0 ? "+" : ""}${delta})`)
          ),
          el("p", { className: "text-hint" },
            delta === 0
              ? "The additional 15 words introduce no new bigram matches. The result is robust to vocabulary curation."
              : `The additional 15 words change overlap by ${delta > 0 ? "+" : ""}${delta} ` +
                `(${overlap34} \u2192 ${overlap49}). ` +
                (Math.abs(delta) <= 2
                  ? "This marginal change suggests the result is robust to vocabulary curation. "
                  : "") +
                "The MC p-value for the full 49-word set is computed in the Extended Analysis section."
          ),
          el("details", {},
            el("summary", {}, "Excluded words (15)"),
            el("ul", {},
              ...LINEAR_A_EXCLUDED.map(w =>
                el("li", { className: "mono" }, `${w.w} — ${w.note}`)
              )
            )
          )
        );
      })()
    )
  );
}
