// AUTO-GENERATED BY scripts/stage-public.mjs — DO NOT EDIT BY HAND.
// Source of truth: scripts/<name>.mjs in the internal monorepo.
// Path references rewritten so the public repo can be self-contained.

// verify-prose: validate that every p-value-shaped decimal in the
// authoritative public-facing documents matches a value from the
// canonical manifest (scripts/canonical-values.json). Fails loudly if
// a number drifted (e.g. an old 0.0498 left behind after the Sign-17
// adjacency-breaking fix turned the canonical value into 0.0562).
//
// This complements verify-docs.mjs (which detects an explicit list of
// known stale tokens) by being engine-driven: the allowed set is
// derived from the live canonical manifest, not maintained by hand.
//
// Exemptions are supported via <!-- canonical-exempt:start --> ...
// <!-- canonical-exempt:end --> blocks for legitimately non-canonical
// decimals (e.g. illustrative examples, unrelated dates).

import { readFileSync, existsSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");
const MANIFEST_PATH = join(__dirname, "canonical-values.json");

// Significance thresholds and other common decimals that legitimately
// appear in prose but are not canonical results. Keep this list short
// and only extend with values that are obviously not study outputs.
const THRESHOLD_ALLOWLIST = new Set([
  "0.001", "0.005", "0.01", "0.010", "0.025", "0.05", "0.050",
  "0.10", "0.100", "0.5", "0.50", "0.500", "0.95", "0.950",
  "0.99", "0.990", "0.999",
  "1.0", "1.00", "1.000",
  // 5% / 10% / 1% as percentage strings show up in "α = 0.05" prose.
  "1%", "5%", "10%",
]);

// Patterns that signal a number is a top-level canonical p-value or
// Spearman rho - the dominant drift surface in independent reviews.
// We intentionally do NOT scan every decimal in prose: Bayes factors,
// bootstrap CI bounds, positional bigram p-values, and KS D statistics
// are derived results that don't currently live in the manifest, and
// flagging them here produces noise without catching the cycle-driving
// review findings. Future tightening can either expand the manifest
// (preferred) or extend this pattern set with new context anchors.
//
// Capture group 1 is the numeric token to validate. We only match
// EXACT-equality operators (=, ≈, ~) so qualitative bounds like
// "p < 0.0001" and "p > 0.70" are not flagged - they are upper/lower
// bounds, not assertions of a specific canonical p-value.
const PVALUE_CONTEXT_PATTERNS = [
  // Canonical p naming: "p = 0.0318", "p ≈ 0.318", "p ~ 0.03", "p-value = 0.0318".
  /\bp(?:[\-\u2010-\u2015]value)?\s*[=≈~]\s*(0?\.\d{2,4})\b(?!%)/g,
  // Adjective-prefixed p-values: "MC p = ...", "FW p = ...", "Holm p = ...",
  // "uniform circularity p = ...", "frequency-weighted circularity p = ...".
  /\b(?:MC|FW|Holm|uniform circularity|frequency[-\s]weighted circularity)\s+p\s*[=≈~]\s*(0?\.\d{2,4})\b(?!%)/gi,
  // Spearman rho values.
  /\b(?:Spearman\s+(?:rho|ρ)|ρ)\s*[=≈]\s*(-?0?\.\d{1,4})\b(?!%)/g,
  // Bold-emphasized 4-decimal numbers ("**0.0318**") - reviewers consistently
  // flag bolded canonical numbers because they're the eye-catching drift surface.
  /\*\*(0?\.\d{4})\*\*/g,
  // Bold-emphasized percentages with at least one decimal ("**3.18%**").
  /\*\*(\d{1,2}\.\d{1,2}%)\*\*/g,
];

const TARGET_FILES = [
  "docs/paper_draft.md",
  "docs/plain_language_summary.md",
  "docs/methodology.md",
  "docs/sign_catalog.md",
  "docs/linear_a_correspondences.md",
  "README.md",
];

function buildAllowedSet(manifest) {
  const out = new Set();
  // Numeric values to fan out into rounded variants. We accept a
  // canonical x at any of {4dp, 3dp, 2dp} truncation/rounding plus
  // its percent form {2dp, 1dp, 0dp}. Anything else for that x is
  // either drift (caught) or exempt (silenced).
  function addNumber(x) {
    if (typeof x !== "number" || !Number.isFinite(x)) return;
    out.add(x.toFixed(4));
    out.add(x.toFixed(3));
    out.add(x.toFixed(2));
    // Percent form: 0.0318 -> 3.18% / 3.2% / 3%.
    const pct = x * 100;
    out.add(pct.toFixed(2) + "%");
    out.add(pct.toFixed(1) + "%");
    out.add(pct.toFixed(0) + "%");
    // Trailing-zero strip: 0.0560 should match 0.056.
    out.add(stripTrailingZeros(x.toFixed(4)));
    out.add(stripTrailingZeros(x.toFixed(3)));
    out.add(stripTrailingZeros(x.toFixed(2)));
  }
  for (const r of manifest.comparison) {
    addNumber(r.pValue);
    addNumber(r.fwPValue);
    addNumber(r.holmP);
    addNumber(r.hyperP);
  }
  addNumber(manifest.sign02.det.pValue);
  addNumber(manifest.sign02.phon.pValue);
  addNumber(manifest.sign18rju.pValue);
  addNumber(manifest.circularity.uniformP);
  addNumber(manifest.circularity.freqWeightedP);
  addNumber(manifest.circularity.spearmanRho);
  for (const s of manifest.circularity.tierSweep) addNumber(s.freqWeightedP);
  addNumber(manifest.leavePD.full.pValue);
  addNumber(manifest.leavePD.filtered.pValue);
  addNumber(manifest.leavePD.droppedFraction);
  addNumber(manifest.fullCorpus.pValue);
  if (manifest.reversal) {
    addNumber(manifest.reversal.forwardP);
    addNumber(manifest.reversal.reversedP);
  }
  return out;
}

function stripTrailingZeros(s) {
  if (!s.includes(".")) return s;
  return s.replace(/0+$/, "").replace(/\.$/, "");
}

// Mask spans so their contents are skipped without disturbing line/col
// offsets. We support two markers:
//   <!-- canonical-exempt:start --> ... <!-- canonical-exempt:end -->
//     for blocks that intentionally contain non-canonical numbers
//     (illustrative examples, unrelated dates, etc.).
//   <!-- historical --> on a line
//     for prose that explicitly retains a superseded canonical value
//     to preserve the audit trail (e.g. "an earlier release reported
//     0.297"). The whole line is masked.
function maskExemptions(text) {
  let masked = text.replace(
    /<!--\s*canonical-exempt:start\s*-->[\s\S]*?<!--\s*canonical-exempt:end\s*-->/g,
    (m) => m.replace(/[^\n]/g, " "),
  );
  masked = masked.split("\n").map((line) => (
    /<!--\s*historical\s*-->/.test(line) ? line.replace(/./g, " ") : line
  )).join("\n");
  return masked;
}

function lineColFromOffset(text, offset) {
  let line = 1, col = 1;
  for (let i = 0; i < offset; i++) {
    if (text[i] === "\n") { line++; col = 1; }
    else col++;
  }
  return { line, col };
}

function normalizeToken(token) {
  // Strip a leading lone "." so ".05" matches "0.05" in the allowlist.
  if (token.startsWith(".")) return "0" + token;
  // Strip leading minus for canonical-rho lookups; rho is signed but the
  // manifest stores |rho|. Treat them identically.
  if (token.startsWith("-")) return token.slice(1);
  return token;
}

function checkFile(absPath, allowed) {
  const raw = readFileSync(absPath, "utf8");
  const text = maskExemptions(raw);
  const findings = [];

  for (const re of PVALUE_CONTEXT_PATTERNS) {
    re.lastIndex = 0;
    let m;
    while ((m = re.exec(text)) !== null) {
      const captured = m[1];
      const token = normalizeToken(captured);
      if (THRESHOLD_ALLOWLIST.has(token)) continue;
      if (allowed.has(token)) continue;
      // The capture starts somewhere inside the full match. Compute its
      // absolute offset for accurate line/col reporting.
      const captureStart = m.index + m[0].indexOf(captured);
      const { line, col } = lineColFromOffset(text, captureStart);
      findings.push({ token: captured, line, col, context: m[0] });
    }
  }
  return findings;
}

function main() {
  if (!existsSync(MANIFEST_PATH)) {
    console.error(`verify-prose: canonical-values.json not found at ${MANIFEST_PATH}`);
    console.error(`              Run: node scripts/generate-canonical-values.mjs`);
    process.exit(1);
  }
  const manifest = JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
  const allowed = buildAllowedSet(manifest);

  let totalFindings = 0;
  let scannedFiles = 0;
  console.log(`verify-prose: scanning ${TARGET_FILES.length} files against canonical manifest (schema v${manifest.schemaVersion})\n`);

  for (const rel of TARGET_FILES) {
    const abs = join(REPO_ROOT, rel);
    if (!existsSync(abs)) {
      // Public mirror may not exist in dev checkouts; skip silently.
      continue;
    }
    scannedFiles++;
    const findings = checkFile(abs, allowed);
    if (findings.length === 0) {
      console.log(`PASS  ${rel}`);
      continue;
    }
    totalFindings += findings.length;
    for (const f of findings) {
      console.log(`FAIL  ${rel}:${f.line}:${f.col}  '${f.token}' in '${f.context.trim()}' is not a current canonical value`);
    }
  }

  console.log("");
  if (totalFindings === 0) {
    console.log(`verify-prose: all ${scannedFiles} files clean`);
    process.exit(0);
  }
  console.log(`verify-prose: ${totalFindings} drift finding(s) across ${scannedFiles} files`);
  console.log(`Hint: regenerate the manifest with:`);
  console.log(`  node scripts/generate-canonical-values.mjs`);
  console.log(`Or, if a value is intentionally non-canonical, wrap it in:`);
  console.log(`  <!-- canonical-exempt:start --> ... <!-- canonical-exempt:end -->`);
  process.exit(1);
}

main();
