// AUTO-GENERATED BY scripts/stage-public.mjs — DO NOT EDIT BY HAND.
// Source of truth: scripts/<name>.mjs in the internal monorepo.
// Path references rewritten so the public repo can be self-contained.

// verify-framing: enforce intellectual-honesty conventions in
// public-facing documentation.
//
// Independent reviews repeatedly flag specific phrases as overclaiming
// (e.g. "passes the test", "definitively rules out", "impressive
// agreement") because the underlying statistical results are
// suggestive, multiply-tested, and dependent on annotation choices.
// The honest paraphrases ("the only candidate that survives the
// uniform null", "are not supported by the same test", "is sensitive
// to ...") are codified as the project standard. This gate fails CI
// loudly if a banned phrase reappears in the scanned docs without an
// explicit allowlist marker.
//
// To intentionally retain a banned phrase (e.g. when quoting another
// author or paraphrasing the banned form to refute it), wrap the
// surrounding span in:
//   <!-- framing-allowed:start --> ... <!-- framing-allowed:end -->
// Reasons should be made obvious from the prose context.

import { readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");

const TARGET_FILES = [
  "docs/paper_draft.md",
  "docs/plain_language_summary.md",
  "docs/methodology.md",
  "docs/sign_catalog.md",
  "docs/linear_a_correspondences.md",
  "docs/prior_decipherment_attempts.md",
  "README.md",
];

// Each rule has:
//   pattern: case-insensitive regex (added /gi at scan time).
//   why:     short reviewer-facing explanation.
//   suggest: an honest paraphrase to consider.
const BANNED_PHRASES = [
  {
    pattern: /\bpasses the (?:bigram )?test\b/,
    why: "claims a positive verdict without the multiple-testing / sensitivity caveats",
    suggest: 'use "is the only candidate that survives the uniform null" or similar',
  },
  {
    pattern: /\bdefinitively rules out\b/,
    why: "asserts elimination beyond what an exploratory bigram test can support",
    suggest: 'use "is not supported by this test" or "fails this specific test"',
  },
  {
    pattern: /\bdefinitively (?:proves|shows|confirms)\b/,
    why: "asserts confirmation beyond what an exploratory test can support",
    suggest: 'use "the data are consistent with" or "suggestive of"',
  },
  {
    pattern: /\b(?:we|this paper|the disc) (?:proves|prove|proven|disproves|disprove|disproven)\b/,
    why: "claims proof; statistical hypothesis tests do not prove",
    suggest: 'use "is consistent with", "supports", or "is suggestive of"',
  },
  {
    pattern: /\bimpressive\b/,
    why: "evaluative adjective inappropriate for a study reporting suggestive evidence",
    suggest: 'use "non-trivial", "non-zero", or simply state the effect size',
  },
  {
    pattern: /\bremarkable\b/,
    why: "evaluative adjective; use neutral language",
    suggest: 'use "notable" or simply state the effect',
  },
  {
    pattern: /\bdecipherment of the (?:phaistos )?disc\b/,
    why: "frames the work as a decipherment; this study reads candidate values, it does not decipher",
    suggest: 'use "phonetic reading of the disc" or "candidate reading"',
  },
  {
    pattern: /\bdecipherment is\b/,
    why: "asserts a decipherment; this study presents a candidate reading",
    suggest: 'use "the candidate reading is" or "the phonetic reading is"',
  },
  {
    pattern: /\bbeyond reasonable doubt\b/,
    why: "courtroom standard inappropriate for an exploratory statistical test",
    suggest: 'use "consistent with the data" or "suggested by the data"',
  },
  {
    pattern: /\bclearly demonstrates\b/,
    why: "clarity adverb pre-supposes the conclusion",
    suggest: 'use "is consistent with" or "supports the interpretation that"',
  },
  {
    pattern: /\bthe disc is (?:not |a |an )?Minoan\b/,
    why: "identity claim; the study tests vocabulary overlap, not language identity",
    suggest: 'use "the phonetic reading is consistent with Minoan" or similar',
  },
  {
    pattern: /\bthree tests,?\s*all passed\b/,
    why: "claims unconditional pass on multiple tests; ignores caveats and failed corrections",
    suggest: 'use "three additional checks; the reading remains internally consistent under each" or similar',
  },
  {
    pattern: /\bhold\s*up under (?:every|all) (?:model|test|correction)/,
    why: "asserts robustness under all models / corrections; the headline Minoan result fails Holm, FW, Sign-02-phonetic, and leave-PD ablation",
    suggest: 'use "the eight non-Minoan eliminations are unaffected by these corrections" (avoid claiming the positive Minoan result is unaffected)',
  },
  {
    pattern: /\bfail no matter how we test (?:them|it)\b/,
    why: "absolute failure claim; the eight eliminations are robust under the tests applied here, but other tests (different sign-value systems, larger reference corpora, alternative statistics) could change verdicts",
    suggest: 'use "fail under each of the corrections applied here" or similar',
  },
  {
    pattern: /\bevery (?:model|null|test) and (?:correction|model|null)\b/,
    why: "absolute robustness claim; spell out which models / corrections are meant",
    suggest: 'use "the eight eliminations survive Holm correction and the frequency-weighted null" (concrete) or similar',
  },
  {
    pattern: /\b(?:a |an )?strong match\b/,
    why: "evaluative absolute; the underlying p-values are not strong by conventional thresholds (Holm > 0.05, FW > 0.7, leave-PD > 0.25)",
    suggest: 'use "non-trivial overlap" or simply state the count and the corresponding p-value',
  },
];

function maskAllowedSpans(text) {
  // Same line/col preservation trick as verify-prose.
  return text.replace(
    /<!--\s*framing-allowed:start\s*-->[\s\S]*?<!--\s*framing-allowed:end\s*-->/g,
    (m) => m.replace(/[^\n]/g, " "),
  );
}

function lineColFromOffset(text, offset) {
  let line = 1, col = 1;
  for (let i = 0; i < offset; i++) {
    if (text[i] === "\n") { line++; col = 1; }
    else col++;
  }
  return { line, col };
}

function checkFile(absPath) {
  const raw = readFileSync(absPath, "utf8");
  const text = maskAllowedSpans(raw);
  const findings = [];
  for (const rule of BANNED_PHRASES) {
    const re = new RegExp(rule.pattern.source, "gi");
    let m;
    while ((m = re.exec(text)) !== null) {
      const { line, col } = lineColFromOffset(text, m.index);
      findings.push({ line, col, match: m[0], why: rule.why, suggest: rule.suggest });
    }
  }
  return findings;
}

function main() {
  let totalFindings = 0;
  let scannedFiles = 0;
  console.log(`verify-framing: scanning ${TARGET_FILES.length} files for banned phrases\n`);

  for (const rel of TARGET_FILES) {
    const abs = join(REPO_ROOT, rel);
    if (!existsSync(abs)) continue;
    scannedFiles++;
    const findings = checkFile(abs);
    if (findings.length === 0) {
      console.log(`PASS  ${rel}`);
      continue;
    }
    totalFindings += findings.length;
    for (const f of findings) {
      console.log(`FAIL  ${rel}:${f.line}:${f.col}  '${f.match}'`);
      console.log(`      why:     ${f.why}`);
      console.log(`      suggest: ${f.suggest}`);
    }
  }

  console.log("");
  if (totalFindings === 0) {
    console.log(`verify-framing: all ${scannedFiles} files clean`);
    process.exit(0);
  }
  console.log(`verify-framing: ${totalFindings} banned-phrase finding(s) across ${scannedFiles} files`);
  console.log(`Hint: rephrase using the suggestions above, or wrap in:`);
  console.log(`  <!-- framing-allowed:start --> ... <!-- framing-allowed:end -->`);
  console.log(`when the banned phrase is intentional (e.g. quoting another author).`);
  process.exit(1);
}

main();
