// AUTO-GENERATED BY scripts/stage-public.mjs — DO NOT EDIT BY HAND.
// Source of truth: scripts/<name>.mjs in the internal monorepo.
// Path references rewritten so the public repo can be self-contained.

// Documentation-claim verifier.
//
// Greps documentation files for known *superseded* canonical values and fails
// the run if any appear outside an explicitly-marked historical block. This
// is the project's lint defence against numerical drift in prose.
//
// Why it exists
// -------------
// `verify-canonical.mjs` checks the engine and the app's PRE_COMPUTED
// constants. It does NOT check markdown prose. The same values are repeated
// across ~15 documents (paper drafts, hypothesis files, decipherment strategy,
// public docs, the SKILL file, README), and a partial regeneration cycle has
// historically left some files updated and others stale. This script closes
// that gap.
//
// How it works
// ------------
// 1. STALE_TOKENS lists the *exact substring* of values that the canonical
//    engine no longer produces (e.g. "0.028" for the old Minoan p-value).
//    Each entry has a current replacement and a brief reason.
// 2. SCANNED_GLOBS lists the file globs we care about (markdown documentation,
//    SKILL files, READMEs).
// 3. EXEMPT_FILES are paths whose stale-value mentions are intentional:
//    review documents (which are records of findings) and progress logs
//    (which record what was true at the time of writing).
// 4. Every token match outside an exempt path or an explicitly-marked
//    historical region (delimited by HTML-comment markers
//    `<!-- historical-values -->` ... `<!-- /historical-values -->`,
//    or single lines tagged with `<!-- historical -->`) is reported as
//    a failure.
//
// Adding a new stale value
// ------------------------
// When a canonical value changes, add the OLD value here. The replacement
// reason makes future contributors look in the right place if a hit
// reappears.
//
// Running
// -------
//   node scripts/verify-docs.mjs            # repository root
//   cd public && npm run verify-docs        # convenience alias

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, "..");

// Each token: a raw substring (NOT a regex) that should not appear in scanned
// docs, plus the current replacement and a reason. Matching uses literal
// substring containment, so "0.028" will also match "0.0283" — which is
// intentional: 0.0283 is also an obsolete Minoan p-value (it has been
// superseded by 0.0318 after the Sign-17 adjacency-breaking fix).
//
// Rounded-form tokens (e.g. "0.159" for Luwian rounded to 3 dp) are listed
// alongside their long-form counterparts so the failure report points at
// whichever form the document uses rather than always at the long-form alias.
const STALE_TOKENS = [
  { token: "0.028",  current: "0.0318 (Minoan MC p) or 0.0307 (Sign 18 RJU)",
    reason: "Minoan MC p was 0.028/0.0283 before the Sign-17 adjacency-breaking fix (April 2026)." },
  { token: "2.8%",   current: "3.18% (Minoan MC p as a percentage)",
    reason: "Minoan MC p was 2.83% before the Sign-17 fix; the post-fix percentage is 3.18%." },
  { token: "0.0498", current: "0.0562 (Sign 02 phonetic MC p)",
    reason: "Sign 02 phonetic MC p shifted after the Sign-17 adjacency-breaking fix (April 2026)." },
  { token: "0.254",  current: "0.286 (Minoan Holm p)",
    reason: "Holm-corrected Minoan p shifted after the Sign-17 fix (April 2026)." },
  { token: "0.712",  current: "0.706 (Minoan FW p)",
    reason: "Frequency-weighted Minoan p shifted after the Sign-17 fix (April 2026)." },
  { token: "0.1594", current: "0.1765 (Luwian MC p, Daidalika sign values)",
    reason: "Luwian MC p shifted after the Sign-17 fix (April 2026)." },
  { token: "0.159",  current: "0.176 (Luwian MC p, rounded to 3 dp)",
    reason: "Luwian MC p rounded to 3 dp shifted from 0.159 to 0.176 after the Sign-17 fix (April 2026)." },
  { token: "0.6192", current: "0.6362 (Mycenaean Greek MC p)",
    reason: "Greek MC p shifted after the Sign-17 fix (April 2026)." },
  { token: "0.619",  current: "0.636 (Greek MC p, rounded to 3 dp)",
    reason: "Greek MC p rounded to 3 dp shifted from 0.619 to 0.636 after the Sign-17 fix (April 2026)." },
  { token: "0.7045", current: "0.7188 (Proto-Finno-Ugric MC p)",
    reason: "PFU MC p shifted after the Sign-17 fix (April 2026)." },
  { token: "0.704",  current: "0.719 (PFU MC p, rounded to 3 dp)",
    reason: "PFU MC p rounded to 3 dp shifted from 0.704 to 0.719 after the Sign-17 fix (April 2026)." },
  { token: "0.7994", current: "0.8102 (Hurrian MC p)",
    reason: "Hurrian MC p shifted after the Sign-17 fix (April 2026)." },
  { token: "0.799",  current: "0.810 (Hurrian MC p, rounded to 3 dp)",
    reason: "Hurrian MC p rounded to 3 dp shifted from 0.799 to 0.810 after the Sign-17 fix (April 2026)." },
  { token: "0.9872", current: "0.9880 (West Semitic MC p)",
    reason: "Semitic MC p shifted after the Sign-17 fix (April 2026)." },
  { token: "0.987",  current: "0.988 (Semitic MC p, rounded to 3 dp)",
    reason: "Semitic MC p rounded to 3 dp shifted from 0.987 to 0.988 after the Sign-17 fix (April 2026)." },
  { token: "0.297",  current: "0.257 (circularity Spearman ρ)",
    reason: "Spearman ρ shifted after switching from no-ties closed form to Pearson on rank vectors (April 2026)." },
];

// Files we scan. These are project documentation surfaces where prose drift
// can outrun the engine.
const SCANNED_GLOBS = [
  "docs/*.md",
  "README.md",
];

// Files where stale-value mentions are intentional (review notes, progress
// logs, the SKILL.md "values that have been wrong before" section, etc.).
// The matcher tests both forward-slash and back-slash forms so it works on
// Windows and POSIX paths.
const EXEMPT_PATTERNS = [
  /[\\/].+[-_]review\.md$/i,
  /[\\/]CRITICAL_REVIEW\.md$/i,
  /[\\/]critical_review\.md$/i,
  /[\\/]audit_findings\.md$/i,
  /[\\/]app-review\.md$/i,
  /[\\/]09_todo\.md$/i,
  /[\\/]07_progress_log\.md$/i,
  /[\\/]04_comparanda\.md$/i,
];

// Lines containing this case-insensitive marker are treated as historical
// context and are skipped. Useful for "was X, now Y" change logs.
const LINE_MARKER = /<!--\s*historical\s*-->/i;
// Multi-line block markers.
const BLOCK_OPEN = /<!--\s*historical-values\s*-->/i;
const BLOCK_CLOSE = /<!--\s*\/historical-values\s*-->/i;

function isExempt(relPath) {
  return EXEMPT_PATTERNS.some(re => re.test(relPath));
}

function expandGlob(glob) {
  // Minimal glob: only supports `dir/*.ext` and `dir/**/*.ext`. We avoid the
  // fast-glob dependency for parity with the rest of `scripts/`.
  const parts = glob.split("/");
  const lastIdx = parts.length - 1;
  const filePattern = parts[lastIdx];
  const dirParts = parts.slice(0, lastIdx);
  const recursive = dirParts.includes("**");
  const baseDir = path.join(REPO_ROOT, ...dirParts.filter(p => p !== "**"));
  if (!fs.existsSync(baseDir)) return [];
  if (filePattern.includes("*")) {
    const ext = filePattern.startsWith("*.") ? filePattern.slice(1) : null;
    const out = [];
    walk(baseDir, recursive, (full) => {
      if (ext && full.endsWith(ext)) out.push(full);
      else if (!ext && path.basename(full) === filePattern) out.push(full);
    });
    return out;
  }
  const candidate = path.join(baseDir, filePattern);
  return fs.existsSync(candidate) ? [candidate] : [];
}

function walk(dir, recursive, onFile) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (recursive) walk(full, true, onFile);
      continue;
    }
    if (entry.isFile()) onFile(full);
  }
}

function scanFile(absPath) {
  const relPath = path.relative(REPO_ROOT, absPath);
  if (isExempt(relPath)) return [];
  const text = fs.readFileSync(absPath, "utf8");
  const lines = text.split(/\r?\n/);
  const findings = [];
  let inHistoricalBlock = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (BLOCK_OPEN.test(line)) inHistoricalBlock = true;
    if (BLOCK_CLOSE.test(line)) { inHistoricalBlock = false; continue; }
    if (inHistoricalBlock) continue;
    if (LINE_MARKER.test(line)) continue;
    for (const { token, current, reason } of STALE_TOKENS) {
      if (line.includes(token)) {
        findings.push({
          file: relPath.replace(/\\/g, "/"),
          line: i + 1,
          token,
          current,
          reason,
          context: line.trim().slice(0, 200),
        });
      }
    }
  }
  return findings;
}

function main() {
  const files = new Set();
  for (const glob of SCANNED_GLOBS) {
    for (const f of expandGlob(glob)) files.add(f);
  }

  let totalFindings = 0;
  const byFile = new Map();
  for (const f of files) {
    const findings = scanFile(f);
    if (findings.length === 0) continue;
    byFile.set(f, findings);
    totalFindings += findings.length;
  }

  if (totalFindings === 0) {
    console.log(`verify-docs: scanned ${files.size} files, no stale canonical values found.`);
    process.exit(0);
  }

  console.log(`verify-docs: FAIL — ${totalFindings} stale canonical-value mention(s) in ${byFile.size} file(s).`);
  console.log("");
  for (const [file, findings] of byFile) {
    const rel = path.relative(REPO_ROOT, file).replace(/\\/g, "/");
    console.log(`  ${rel}`);
    for (const f of findings) {
      console.log(`    line ${f.line}: "${f.token}" — replace with ${f.current}`);
      console.log(`      reason: ${f.reason}`);
      console.log(`      context: ${f.context}`);
    }
    console.log("");
  }
  console.log("Permitted exemptions: review notes, progress logs, anything inside");
  console.log("<!-- historical-values --> ... <!-- /historical-values --> blocks, or single");
  console.log("lines tagged with <!-- historical -->.");
  process.exit(1);
}

main();
